### ISSUE TITLE
Item list width issue

### ISSUE THREAD

**Issue by iamfarmankhan** [AhmedLSayed9/dropdown_button2#1]
Hi @AhmedLSayed9 at first thank you so much for making such helpful widget. Currently I am facing one issue with this widget.

<img width="308" alt="Screenshot 2021-12-06 at 10 15 00 PM" src="https://user-images.githubusercontent.com/19756500/144886728-c3598e4a-f797-42e1-b292-37803c446f6e.png">
As you can see image options list width not same as dropdown widget. I want to make options list same width as dropdown widget. 

I have tried itemWidth etc but not worked. 

Would you like to help me how to fix that?

Thank you

**Comment by AhmedLSayed9** [comment]
Hi @iamfarmankhan

In your case the dropdown TextFormField takes max width possible like other TextFormFields. If you want the dropdown menu to take same width too, just don't pass itemWidth value (or pass null) and It'll take max width possible too like the dropdown TextFormField.

Please let me know if this helped you.

**Comment by iamfarmankhan** [comment]
Hi @AhmedLSayed9 , thanks for your reply. If I pass null in itemWidth it does not effect any. If I pass double.Infinity dropdown option items not showing. Getting below exception - 

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
BoxConstraints forces an infinite width.

Updated layout information required for RenderAnimatedOpacity#b8abd NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2747 pos 12: '!_needsLayout'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

**Comment by AhmedLSayed9** [comment]
You aren't supposed to pass double.infinity just null or ignoring itemWidth and the widget will automatically calculate width from max width of parent constraints. But I don't know what's different with your code, Can you drop your code please?

**Comment by iamfarmankhan** [comment]
Hi @AhmedLSayed9 , I have just given widget part here. 

return Scaffold(
      body: SingleChildScrollView(
        child: Form(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const SizedBox(
                  height: 35,
                ),
                InkWell(
                  child: const Icon(
                    Icons.arrow_back,
                    color: Colors.black,
                    size: 36,
                  ),
                  onTap: (){
                    Navigator.pop(context,true);
                  },
                ),
                Center(
                  child: Text(
                    'info_about_dog'.tr,
                    style: const TextStyle(
                        fontSize: 22,
                        color: Colors.black,
                        fontWeight: FontWeight.w700),
                    textAlign: TextAlign.center,
                  ),
                ),
                const SizedBox(
                  height: 30,
                ),
                PrimaryTextField(
                  titleText: 'whats_it_called'.tr,
                  textEditingController: dogNameEditingTextController,
                  validator: _notEmptyValidator,
                ),
                Text(
                  'date_of_birth'.tr,
                  style: kTextFieldTitle,
                ),
                const SizedBox(
                  height: kMarginInTitleAndField,
                ),
                Row(
                  children: [
                    SizedBox(
                      width: 60,
                      height: 40,
                      child: InkWell(
                        child: TextView(
                          title: date,
                        ),
                        onTap: ()
                        {
                          showDtePicker(context);
                        },
                      ),
                    ),
                    const SizedBox(
                      width: 20,
                    ),
                    SizedBox(
                      width: 60,
                      height: 40,
                      child: InkWell(
                        child: TextView(
                          title: month,
                        ),
                        onTap: ()
                        {
                          showDtePicker(context);
                        },
                      ),
                    ),
                    const SizedBox(
                      width: 20,
                    ),
                    SizedBox(
                      width: 60,
                      height: 40,
                      child: InkWell(
                        child: TextView(
                          title: year,
                        ),
                        onTap: ()
                        {
                          showDtePicker(context);
                        },
                      ),
                    ),
                  ],
                ),
                const SizedBox(
                  height: kMarginFormField,
                ),
                Text(
                  'male_or_female'.tr,
                  style: kTextFieldTitle,
                ),
                const SizedBox(
                  height: kMarginInTitleAndField,
                ),
                Row(
                  children: [
                    SizedBox(
                      height: 50,
                      child: OutlinedButton(
                        onPressed: () {
                          setState(() {
                            isGenderSelected = true;
                            isMaleSelected = true;
                          });
                        },
                        style: isGenderSelected
                            ? (!isMaleSelected
                            ? getBorderedButtonStyle()
                            : getFilledButtonStyle())
                            : getBorderedButtonStyle(),
                        child: Text(
                          'male'.tr,
                          style: TextStyle(
                              color: isGenderSelected
                                  ? (!isMaleSelected
                                  ? Colors.black
                                  : Colors.white)
                                  : Colors.black,
                              fontWeight: FontWeight.w400,
                              fontSize: 20),
                        ),
                      ),
                    ),
                    const SizedBox(
                      width: 20,
                    ),
                    SizedBox(
                      height: 50,
                      child: OutlinedButton(
                        onPressed: () {
                          setState(() {
                            isGenderSelected = true;
                            isMaleSelected = false;
                          });
                        },
                        style: isGenderSelected
                            ? (isMaleSelected
                            ? getBorderedButtonStyle()
                            : getFilledButtonStyle())
                            : getBorderedButtonStyle(),
                        child: Text(
                          'female'.tr,
                          style: TextStyle(
                              color: isGenderSelected
                                  ? (isMaleSelected
                                  ? Colors.black
                                  : Colors.white)
                                  : Colors.black,
                              fontWeight: FontWeight.w400,
                              fontSize: 20),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(
                  height: kMarginFormField,
                ),
                Text(
                  'are_u_neutered'.tr,
                  style: kTextFieldTitle,
                ),
                const SizedBox(
                  height: kMarginInTitleAndField,
                ),
                Row(
                  children: [
                    SizedBox(
                      height: 50,
                      child: OutlinedButton(
                        onPressed: () {
                          setState(() {
                            isNeuteredSelected = true;
                            isYesSelected = true;
                          });
                        },
                        style: isNeuteredSelected
                            ? (!isYesSelected
                            ? getBorderedButtonStyle()
                            : getFilledButtonStyle())
                            : getBorderedButtonStyle(),
                        child: Text(
                          'yes'.tr,
                          style: TextStyle(
                              color: isNeuteredSelected
                                  ? (!isYesSelected
                                  ? Colors.black
                                  : Colors.white)
                                  : Colors.black,
                              fontWeight: FontWeight.w400,
                              fontSize: 20),
                        ),
                      ),
                    ),
                    const SizedBox(
                      width: 20,
                    ),
                    SizedBox(
                      height: 50,
                      child: OutlinedButton(
                        onPressed: () {
                          setState(() {
                            isNeuteredSelected = true;
                            isYesSelected = false;
                          });
                        },
                        style: isNeuteredSelected
                            ? (isYesSelected
                            ? getBorderedButtonStyle()
                            : getFilledButtonStyle())
                            : getBorderedButtonStyle(),
                        child: Text(
                          'no'.tr,
                          style: TextStyle(
                              color: isNeuteredSelected
                                  ? (isYesSelected
                                  ? Colors.black
                                  : Colors.white)
                                  : Colors.black,
                              fontWeight: FontWeight.w400,
                              fontSize: 20),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(
                  height: 16,
                ),
                Text(
                  'whats_ur_size'.tr,
                  style: kTextFieldTitle,
                ),
                const SizedBox(
                  height: kMarginInTitleAndField,
                ),
                CustomDropdownButton2(
                  hint: sizeHintText,
                  dropdownItems: <String>[
                    'Pequeño'.tr,
                    'medium'.tr,
                    'great'.tr,
                  ],
                  value: sizeValue,
                  onChanged:  (newValue) {
                    setState(() {
                      sizeValue = newValue!;
                      print("Size Value $sizeValue");
                    });
                  },
                  icon:  Image.asset('images/down_arrow.png'),
                  buttonWidth: double.infinity,
                ),
                const SizedBox(
                  height: kMarginFormField,
                ),
                Text(
                  'how_does_it_behave_other_dogs'.tr,
                  style: kTextFieldTitle,
                ),
                const SizedBox(
                  height: kMarginInTitleAndField,
                ),
                CustomDropdownButton2(
                  hint: behaviourHintText,
                  dropdownItems: <String>[
                    'kind'.tr,
                    'playful'.tr,
                    'aggresive'.tr,
                  ],
                  value: behaviourValue,
                  itemWidth: double.infinity,
                  onChanged:  (newValue) {
                    setState(() {
                      behaviourValue = newValue!;
                    });

                  },
                  icon:  Image.asset('images/down_arrow.png'),
                  buttonWidth: double.infinity,
                ),
                const SizedBox(
                  height: 30,
                ),
                PrimaryGreenButton(buttonClickHandler: (){
                  Navigator.of(context).push(MaterialPageRoute(
                      builder: (context) => const CapturePhotoScreen()));
                }, title: 'register_dog'.tr),
              ],
            ),
          ),
        ),
      ),
    );

**Comment by AhmedLSayed9** [comment]
![Capture](https://user-images.githubusercontent.com/70890146/145002252-bea302c3-a2ec-4a66-b457-8e1336b1d8ce.PNG)

Hi @iamfarmankhan,
You're using the Custom widget which I've made with default values for my preferences. You can edit the marked line of code as here it'll give DropdownButton2 default `itemWidth` value of 140 if itemWidth is null. and we want to pass null here, so you should remove `?? 140` so that It'll send the null value instead of the default 140 value.

How to edit the Custom widget to your preferences:
1. Copy the custom widget with inside the package to your lib folder or wherever you want.
2. Change the class name to whatever you want to avoid duplication between your custom widget and package's custom widget.
3. Edit and use it as you want.

Also, There's DropdownButtonFormField2, you can try using it with `Form` as you can add validation, etc.. as shown in the examples.

Good luck!

**Comment by AhmedLSayed9** [comment]
Please, let me know if your problem has been fixed.

**Comment by iamfarmankhan** [comment]
Hi @AhmedLSayed9 , I copied the code for CustomDropDown in my project and removed itemWidth and problem is solved. Thanks for your plugin @AhmedLSayed9 .
