### ISSUE TITLE
Issue with margin of dropdown

### ISSUE THREAD

**Issue by AkshayDexter** [AhmedLSayed9/dropdown_button2#10]
I have started using with my design all going well but when I started giving margins to dropdown it's sets well but when I see the listed items doesn't get the outer margin they always stick to the start not aligned with the main box
![4d046722-1190-4387-903f-c8e3c43df4ae](https://user-images.githubusercontent.com/82798820/155877102-c531ee78-cdb5-47b8-a211-7422d33527e4.jpg)

**Comment by AhmedLSayed9** [comment]
I've tested giving margin to the dropdown button and It's working fine.
Can you provide a sample code of your case? Also, make sure you're setting Offset's dx to 0.

**Comment by AkshayDexter** [comment]
Yes issue with my -20 dx all it's fine now thank you
