### ISSUE TITLE
Align DropDown to end of the button

### ISSUE THREAD

**Issue by buraktabn** [AhmedLSayed9/dropdown_button2#102]
Is there an easy way of doing this?

| Without Offset | `Offset(-dropDownWidth + buttonWidth)` |
| :---: | :---: |
| ![image](https://user-images.githubusercontent.com/49204989/202815342-7831f3f5-7bba-484f-8f03-4457c17c8b1c.png) | ![image](https://user-images.githubusercontent.com/49204989/202815445-87537395-726f-4fd6-9911-69798f293f47.png) |

**Comment by AhmedLSayed9** [comment]
Upgrade to latest version and use `dropdownDirection: DropdownDirection.left`.
