### ISSUE TITLE
Change scrollbar colors

### ISSUE THREAD

**Issue by danielesilvestre** [AhmedLSayed9/dropdown_button2#113]
I need to personalise the scrollbar track and thumb colors, but  I do not found a way to do that.
Maybe You folks can help me with that?

Is there a way to do it with the currently version or this is a feature that maybe need to be implemented?

I could do that only changing in the app core theme for the entire project.

**Comment by AhmedLSayed9** [comment]
It needs to be implemented.
Currently, You can wrap `DropdownButton2` with `Theme` to make changes to its theme without affecting the entire project.

**Comment by muzzah** [comment]
@AhmedLSayed9 So based on the implementation I see here the color properties of the scrollbar theme data have no effect?

**Comment by AhmedLSayed9** [comment]
> @AhmedLSayed9 So based on the implementation I see here the color properties of the scrollbar theme data have no effect?

It works fine at my side. Can you open an issue with a minimal sample that produces the issue?
