### ISSUE TITLE
Force dropdown to open below the button

### ISSUE THREAD

**Issue by EskAere** [AhmedLSayed9/dropdown_button2#117]
> Dropdown menu always open below the button "as long as it's possible otherwise it'll open to the end of the screen" and you can edit its position by using the offset parameter.

Would it be possible to force the dropdown to open below the button ? If tapped while the dropdown is near the end of the screen, it feels buggy. 
Any idea if we could auto scroll the page ? 

Thanks for this plugin btw !!

**Comment by AhmedLSayed9** [comment]
This is not possible.
Dropdown menu is open as new PopupRoute and has no relation to the previous Route.
It's not a bug. That's the expected behavior even with normal DropdownButton from Flutter.

**Comment by EskAere** [comment]
Thank you for the answer. 
I know it is not a bug, I just wanted to know if there was a way to do it. 
That's what my clients want 🤷‍♂️ I'll find a way !
