### ISSUE TITLE
Dynamic DropdownWidth

### ISSUE THREAD

**Issue by Albjon30** [AhmedLSayed9/dropdown_button2#119]
DropdownButton doesn't get dynamic width. It needs to get the width based on the content width.

**Comment by AhmedLSayed9** [comment]
If both `buttonWidth` & `dropdownWidth` is null (or not used), their width will be calculated from the maximum width of items or hint text (dynamic width).

If you manually set `buttonWidth` then dropdown menu width will be equal to button's width. In that case, you can only use `dropdownWidth` to set different width to the menu but it can't be dynamic.

**Comment by maxgmer** [comment]
@AhmedLSayed9 does it work with customButton? Didn't set width anywhere and it still takes the width of the button, not the max width of the items.
