### ISSUE TITLE
[Request] Make it possible to flip the arrows when opening the drop-down menu.

### ISSUE THREAD

**Issue by zorro901** [AhmedLSayed9/dropdown_button2#12]
![Screenshot_1646206997 - コピー](https://user-images.githubusercontent.com/11729927/156324125-27abd530-db13-493f-930b-a8d4cff6b583.png)

If you use onTap, you can't flip the arrow when you select something other than a menu item.

**Comment by AhmedLSayed9** [comment]
You can use `iconOnClick` now to show different icon when menu open.
