### ISSUE TITLE
sometimes the selected value is not showing in the dropdown button

### ISSUE THREAD

**Issue by sanjay-023** [AhmedLSayed9/dropdown_button2#120]
when selecting an option from the dropdown its not showing the selected value in the dropdown button ,its showing as blank. This issue mostly happens on multiselect dropdown. On single select also it happens but not all the times.

**Comment by AhmedLSayed9** [comment]
Can you please provide a working sample that produces the issue?

**Comment by sanjay-023** [comment]
Sure I will attach screenshot or screen recording of the same in my next
email.

**Comment by AhmedLSayed9** [comment]
screenshot or screen recording is not enough. I need a working sample that produces that issue

**Comment by sanjay-023** [comment]
Working sample means? I didn’t get you

**Comment by AhmedLSayed9** [comment]
A sample that I can run and produce the issue.

**Comment by sanjay-023** [comment]
But it doesn’t happen all the time.

**Comment by AhmedLSayed9** [comment]
Then how can I know & fix the issue ? 😅

**Comment by AhmedLSayed9** [comment]
It might be something wrong with your code.

**Comment by sanjay-023** [comment]
For that I don’t really have an answer but it doesn’t throws any exception
or error.
Does the package have any restriction in using it in a container with a
fixed height?

**Comment by AhmedLSayed9** [comment]
It might be related to that. There's [buttonHeight](https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/DropdownButton2/buttonHeight.html) parameter you can use.
but again, you need to provide a sample code that produces the issue so I can help you.

**Comment by sanjay-023** [comment]
I will remove the container and style the drop-down button using the
existing parameters from the package itself and see whether the issue
happens or not.
Thanks for the reply and support

**Comment by AhmedLSayed9** [comment]
No problem.
Feel free to ask for a re-open with a code sample if you still face an issue.

**Comment by sanjay-023** [comment]
Will do, thanks!
