### ISSUE TITLE
Feature request: Select all option

### ISSUE THREAD

**Issue by felixrzayev** [AhmedLSayed9/dropdown_button2#121]
![image](https://user-images.githubusercontent.com/112754312/217450284-e4d90c0d-18a7-4c8d-97d6-6383440fa470.png)

![image](https://user-images.githubusercontent.com/112754312/217450334-6af27cd7-6d7b-4f85-a9bb-3f23b32342a1.png)

Without search field.

**Comment by anis-mansuri** [comment]
Did anyone figure it out, how to do it select all options?
