### ISSUE TITLE
Hint Text Not working

### ISSUE THREAD

**Issue by lukasmckaine22** [AhmedLSayed9/dropdown_button2#123]
the hint text is not displaying, it is showing the value instead, which is fine, but i cant customize the color, size and style. ignore the controller. it is irrelevant to the issue

class WeekDropDown extends StatelessWidget {
  const WeekDropDown({
    Key? key,
    required this.controller,
  }) : super(key: key);

  final LiveController controller;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: DropdownButtonHideUnderline(
        child: DropdownButton2(
          buttonPadding: const EdgeInsets.symmetric(
            vertical: 6,
            horizontal: 12,
          ),
          buttonHeight: 25,
          buttonDecoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            color: AppColors.kBlue,
          ),
          // hint: Row(
          //   children: [
          //     Text(
          //       'hi',
          //       style: TextStyle(
          //         color: Colors.black,
          //         fontSize: 12,
          //         fontWeight: FontWeight.bold,
          //         fontStyle: FontStyle.italic,
          //       ),
          //     ),
          //   ],
          // ),
          iconSize: 16,
          iconDisabledColor: Colors.black,
          iconEnabledColor: Colors.black,
          dropdownMaxHeight: 600,
          dropdownWidth: 100,
          dropdownDecoration: BoxDecoration(
            borderRadius: BorderRadius.circular(14),
            color: Colors.grey,
          ),
          //offset: Offset(MediaQuery.of(context).size.width * -.10, 0),
          items: List.generate(15, (index) => (index + 1).toString())
              .map<DropdownMenuItem<String>>((String value) {
            return DropdownMenuItem<String>(
              value: value,
              child: Text(
                'Week ${value.toString()}',
              ),
            );
          }).toList(),
          onChanged: (String? value) =>
              controller.updateSelectedItem(value.toString()!),
          value: controller.selectedWeek.value,
        ),
      ),
    );
  }
}

**Comment by AhmedLSayed9** [comment]
You're commenting `hint` argument so it's expected not to work.
Also if `hint` is displayed as a placeholder if value is null and the dropdown is enabled (items and onChanged are non-null) so make sure these are correct with your case.

**Comment by lukasmckaine22** [comment]
Hi. I didn’t have it commented out in my code. I was seeing if I comment out if it would affect the drop-down. The comment out is not the problem. What do you mean by displayed as a placeholder…?Sent from my iPhoneOn Feb 15, 2023, at 06:10, Ahmed Elsayed ***@***.***> wrote:﻿
You're commenting hint argument so it's expected not to work.
Also if hint is displayed as a placeholder if value is null and the dropdown is enabled (items and onChanged are non-null) so make sure these are correct with your case.

**Comment by AhmedLSayed9** [comment]
hint only appears when value is null and the dropdown is enabled (items and onChanged are non-null)

**Comment by AhmedLSayed9** [comment]
is `value: controller.selectedWeek.value` initially is null in your case? can you pass `null` directly and test if hint is displayed?

**Comment by lukasmckaine22** [comment]
Oh I see. I don’t care about hint really. But how can I change the style on the value that is displayed. Sent from my iPhoneOn Feb 15, 2023, at 13:14, Ahmed Elsayed ***@***.***> wrote:﻿
is value: controller.selectedWeek.value initially is null in your case? can you pass null directly and test if hint is displayed?

**Comment by AhmedLSayed9** [comment]
The title of the issue is `Hint Text Not working` so 😛

You can change the style of the selected value by using [selectedItemBuilder](https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/DropdownButton2/selectedItemBuilder.html)

**Comment by lukasmckaine22** [comment]
Thank youSent from my iPhoneOn Feb 15, 2023, at 13:24, Ahmed Elsayed ***@***.***> wrote:﻿
Closed #123 as completed.

**Comment by 3vilcrow** [comment]
I've been experiencing a similar error, but in my case, the selected value is null. The hint is defined, but when I select an item from the dropdown, the onChanged event doesn't get triggered, so the value doesn't get updated.

**Comment by 3vilcrow** [comment]
sure, no problem
