### ISSUE TITLE
Add margin and border radius in selected item

### ISSUE THREAD

**Issue by programmermager** [AhmedLSayed9/dropdown_button2#124]
it would be nice if we can add margin and radius into selected item

**Comment by AhmedLSayed9** [comment]
This can be done by `selectedItemBuilder` or am I missing something here?

**Comment by mehmetext** [comment]
> This can be done by `selectedItemBuilder` or am I missing something here?

I think that he wanted to mean to highlight the selected item in the items list.

![](https://user-images.githubusercontent.com/44941107/219940105-fcfea6c0-807e-4442-9c36-0b759f2a4485.png)

**Comment by programmermager** [comment]
> > This can be done by `selectedItemBuilder` or am I missing something here?
> 
> I think that he wanted to mean to highlight the selected item in the items list.
> 
> ![](https://user-images.githubusercontent.com/44941107/219940105-fcfea6c0-807e-4442-9c36-0b759f2a4485.png)

yes, thats what i mean

**Comment by AhmedLSayed9** [comment]
You can use [selectedItemHighlightColor](https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/DropdownButton2/selectedItemHighlightColor.html)

**Comment by programmermager** [comment]
> You can use [selectedItemHighlightColor](https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/DropdownButton2/selectedItemHighlightColor.html)

but it able to add radius and margin? like this
![image](https://user-images.githubusercontent.com/7869219/220389954-084f2e72-bf8a-40df-bb48-f73548ac9a70.png)


so far i try we can only able to set the color, not the radius and margin. so the output like this
![image](https://user-images.githubusercontent.com/7869219/220390210-2f15131d-5e11-4cbb-957e-b37bd2c9a0d7.png)

**Comment by mehmetext** [comment]
@AhmedLSayed9 can we add custom widget by controlling like `selectedValue == DropdownItem.value`?

**Comment by AhmedLSayed9** [comment]
I'll see what I can do

**Comment by programmermager** [comment]
thanks @AhmedLSayed9 waiting for good news

**Comment by husainazkas** [comment]
> You can use [selectedItemHighlightColor](https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/DropdownButton2/selectedItemHighlightColor.html)

this property has been removed on the latest version (^2.0.0) so how we migrate this from breaking changes?

**Comment by AhmedLSayed9** [comment]
> this property has been removed on the latest version (^2.0.0) so how we migrate this from breaking changes?

```
menuItemStyleData: MenuItemStyleData(
  selectedMenuItemBuilder: (ctx, child) {
    return Container(
      color: Colors.blue,
      child: child,
    );
  },
),
```
