### ISSUE TITLE
Custom title for selected value is it possible?

### ISSUE THREAD

**Issue by FetFrumos** [AhmedLSayed9/dropdown_button2#127]
I using this model for my DropdownButtonFormField2:

  ```
   class MyItem{
        final String fullName;
        final String shortName; 
     }
```
     
     This my code:
     
  ```
    return DropdownButtonFormField2<MyItem>(
      items: _getItems(),
     );
     
      List<DropdownMenuItem<MyItem>> _getItems() {
    return widget.items
        .map((e) => DropdownMenuItem(
              value: e,
              child: Container(
                color: AppColors.inputBackgroundColor,
                alignment: Alignment.centerLeft,
                child: Text(
                  '${e.fullName} (${e.shortName})',
                  style: AppStyles.bodyText1,
                ),
              ),
            ))
        .toList();
  }
     
```

so I need to display  "fullName (shortName)" in the popup(items),
and only the "shortName" in the input field itself (when I selected the value).

is this possible?

**Comment by AhmedLSayed9** [comment]
Yes.
You just need some unique value to be used for your DropdownMenuItem. `i.e: value: e.fullName,`
If your full name is unique then use it or maybe add some `id` to your `MyItem` class or let your class implement value based equality by overriding `operator ==` and `hashCode`.
