### ISSUE TITLE
Bug: unable to add Custom Items Heights for Multi Item Select DropDown

### ISSUE THREAD

**Issue by dhirajhimani** [AhmedLSayed9/dropdown_button2#134]
Issue comes when the last items are selected, 

For reproducing we can use the examples - https://pastebin.com/iP8F6H0L

 DropdownButton2 as Multiselect Dropdown with Checkboxes with items of different heights like dividers

` Error: 'package:flutter/src/rendering/stack.dart': Failed assertion: line 749 pos 12: 'child != null': is not true.
                                 #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
                                 #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
                                 #2      RenderIndexedStack._childAtIndex (package:flutter/src/rendering/stack.dart:749:12)
                                 #3      RenderIndexedStack.paintStack (package:flutter/src/rendering/stack.dart:776:29)
                                 #4      RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
                                 #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
                                 #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
                                 #7      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
                                 #8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
                                 #9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
                                 #10     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
                                 #11     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1089:7)
                                 #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
                                 #13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
                                 #14     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
                                 #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
                                 #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
                                 #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
                                 #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
                                 #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
                                 #20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15) `

**Comment by dhirajhimani** [comment]
Please could you try this example 
 and select the last items 
 
 ` // ignore_for_file: type=lint

import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/material.dart';

class DummyScreen extends StatefulWidget {
  const DummyScreen({super.key});

  @override
  State<DummyScreen> createState() => _DummyScreenState();
}

class _DummyScreenState extends State<DummyScreen> {
  final List<String> items = [
    'Item1',
    'Item2',
    'Item3',
    'Item4',
    'Item5',
    'Item6',
  ];
  List<String> selectedItems = [];

  @override
  Widget build(BuildContext context) => Scaffold(
        body: Center(
          child: DropdownButtonHideUnderline(
            child: DropdownButton2(
              isExpanded: true,
              hint: Align(
                alignment: AlignmentDirectional.center,
                child: Text(
                  'Select Items',
                  style: TextStyle(
                    fontSize: 14,
                    color: Theme.of(context).hintColor,
                  ),
                ),
              ),
              items: _addDividersAfterItems(items),
              //Use last selected item as the current value so if we've limited menu height, it scroll to last item.
              value: selectedItems.isEmpty ? null : selectedItems.last,
              onChanged: (value) {},
              selectedItemBuilder: (context) {
                return items.map(
                  (item) {
                    return Container(
                      alignment: AlignmentDirectional.center,
                      padding: const EdgeInsets.symmetric(horizontal: 16.0),
                      child: Text(
                        selectedItems.join(', '),
                        style: const TextStyle(
                          fontSize: 14,
                          overflow: TextOverflow.ellipsis,
                        ),
                        maxLines: 1,
                      ),
                    );
                  },
                ).toList();
              },
              menuItemStyleData: MenuItemStyleData(
                padding: const EdgeInsets.symmetric(horizontal: 8.0),
                customHeights: _getCustomItemsHeights(),
              ),
            ),
          ),
        ),
      );

  List<DropdownMenuItem<String>> _addDividersAfterItems(List<String> items) {
    List<DropdownMenuItem<String>> _menuItems = [];
    for (var item in items) {
      _menuItems.addAll(
        [
          DropdownMenuItem<String>(
            value: item,
            child: StatefulBuilder(
              builder: (context, menuSetState) {
                final _isSelected = selectedItems.contains(item);
                return InkWell(
                  onTap: () {
                    _isSelected
                        ? selectedItems.remove(item)
                        : selectedItems.add(item);
                    //This rebuilds the StatefulWidget to update the button's text
                    setState(() {});
                    //This rebuilds the dropdownMenu Widget to update the check mark
                    menuSetState(() {});
                  },
                  child: Container(
                    height: double.infinity,
                    padding: const EdgeInsets.symmetric(horizontal: 16.0),
                    child: Row(
                      children: [
                        _isSelected
                            ? const Icon(Icons.check_box_outlined)
                            : const Icon(Icons.check_box_outline_blank),
                        const SizedBox(width: 16),
                        Text(
                          item,
                          style: const TextStyle(
                            fontSize: 14,
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
          //If it's last item, we will not add Divider after it.
          if (item != items.last)
            const DropdownMenuItem<String>(
              enabled: false,
              child: Divider(),
            ),
        ],
      );
    }
    return _menuItems;
  }

  List<double> _getCustomItemsHeights() {
    List<double> _itemsHeights = [];
    for (var i = 0; i < (items.length * 2) - 1; i++) {
      if (i.isEven) {
        _itemsHeights.add(40);
      }
      //Dividers indexes will be the odd indexes
      if (i.isOdd) {
        _itemsHeights.add(4);
      }
    }
    return _itemsHeights;
  }
}
 `

**Comment by dhirajhimani** [comment]
Please could you test this code:- 

[https://pastebin.com/iP8F6H0L](https://pastebin.com/iP8F6H0L)

**Comment by dhirajhimani** [comment]
This is the combination of DropdownButton2 with items of different heights like dividers and Multiselect Dropdown with Checkboxes

**Comment by dhirajhimani** [comment]
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-arm64, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.76.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability`

**Comment by AhmedLSayed9** [comment]
`selectedItemBuilder` is expecting the same length of your items. You're giving it your actual items without dividers (dividers are just disabled items but they should be counted).

I'll try to enhance dividers to not be counted as items or alternatively make `selectedItemBuilder` return a widget instead of List<Widget>.

For now, you should consider adding dividers to your items inside `selectedItemBuilder` and it'll work.

**Comment by giridat** [comment]
@dhirajhimani have you been able to find a workaround? I am facing the same issue.

**Comment by giridat** [comment]
> `selectedItemBuilder` is expecting the same length of your items. You're giving it your actual items without dividers (dividers are just disabled items but they should be counted).
> 
> I'll try to enhance dividers to not be counted as items or alternatively make `selectedItemBuilder` return a widget instead of List.
> 
> For now, you should consider adding dividers to your items inside `selectedItemBuilder` and it'll work.

Unfortunately, even after trying this work around I am facing the same issue too. 

Could you please guide me a little on what im doing wrong?

`` selectedItemBuilder: (context) {
                              return selectedItems.map(
                                (item) {
                                  return Container(
                                    alignment: AlignmentDirectional.center,
                                    child: Column(
                                      children: [
                                        Text(
                                          selectedItems.join(', '),
                                          softWrap: true,
                                          style: const TextStyle(
                                            fontFamily: "Arial",
                                            fontSize: 16,
                                            color: Color.fromRGBO(0, 0, 0, 1),
                                            overflow: TextOverflow.ellipsis,
                                          ),
                                          maxLines: 1,
                                        ),
                                        Divider(),
                                      ],
                                    ),
                                  );
                                },
                              ).toList();``

**Comment by AhmedLSayed9** [comment]
@giridat `selectedItemBuilder` should consider dividers items same as `items`
