### ISSUE TITLE
Searchable Dropdown: Not working in release mode

### ISSUE THREAD

**Issue by SouksavathPMS** [AhmedLSayed9/dropdown_button2#136]

**Comment by SouksavathPMS** [comment]
It's working fine is debugging mode but when i try to run in release mode the search value seem to be not working

**Comment by SouksavathPMS** [comment]
> It's working fine is debugging mode but when i try to run in release mode the search value seem to be not working

Ohh i found the solution :
i currently use DropdownButton2<Model> with Model (Not a String)
so in the : searchMatchFn return 

 (item.value.[YOUR SEARCH VALUE]
                .toString()
                .toLowerCase()
                .contains(searchValue.toLowerCase()))

**Comment by altafShaikh1717** [comment]
I have done same and debug as well , working  while debugging but not working in release mode
