### ISSUE TITLE
Easy way of changing the style of the selected item's text

### ISSUE THREAD

**Issue by Apollo108** [AhmedLSayed9/dropdown_button2#144]
Hi, I'm wondering if there is an easy way of changing the style of the selected item's text (without touching the items in the dropdown itself), besides the **selectedItemBuilder**, which requires a List\<Widget\>? It would be useful to do this via a property, which accepts a TextStyle, for example.

**Comment by AhmedLSayed9** [comment]
What's the problem with `selectedItemBuilder` ?
It's familiar and been used at flutter's DropdownButton.

**Comment by Apollo108** [comment]
The only problem with it - it's not user friendly for this simple case. Any chances of adding the **selectedItemTextStyle** (or something similar) property soon? Or maybe to make it a part of the buttonStyleData... Thanks.

**Comment by AhmedLSayed9** [comment]
The thing is: making `selectedItemTextStyle` will not just update TextStyle of the items but will also ignore the other characteristics applied to `items` like padding, alignment, etc.. so, you'll have to use `selectedItemBuilder` anyway.

**Comment by AhmedLSayed9** [comment]
If you don't want to duplicate `items.map(...).toList()` part at both `items` and `selectedItemBuilder` properties, you can make a helper function that take your `ItemTextStyle` as a parameter and return that list. There's no way to do that internally at the package.

**Comment by Apollo108** [comment]
I'm just wondering, why `selectedItemBuilder` always returns a List\<Widget\>, including the case, where there is only one selected item? What should I do in this case?

**Comment by AhmedLSayed9** [comment]
It allows more flexibility in specifying how a certain selected item is displayed, same as `items`, i.e:
```dart
selectedItemBuilder: (BuildContext context) {
  return items.map<Widget>((String item) {
    if (item == "something")
      return Text(
        item,
        style: TextStyle(color: Colors.red),
      );
    return Text(item);
  }).toList();
},
```
That'll show text in red only when `something` item is selected.

If you don't care and want to show the same for all items then just return the same widget for all items.

**Comment by Apollo108** [comment]
Thank you anyway)
