### ISSUE TITLE
The getter 'View' isn't defined for the class 'DropdownButton2State<T>

### ISSUE THREAD

**Issue by Yoda-Man** [AhmedLSayed9/dropdown_button2#145]
/C:/Users/trust/AppData/Roaming/Pub/Cache/hosted/pub.dev/dropdown_button2-2.1.1/lib/src/dropdown_button2.dart:1503:25: Error: The getter 'View' isn't defined for the class 'DropdownButton2State<T>'.
 - 'DropdownButton2State' is from 'package:dropdown_button2/src/dropdown_button2.dart' ('/C:/Users/trust/AppData/Roaming/Pub/Cache/hosted/pub.dev/dropdown_button2-2.1.1/lib/src/dropdown_button2.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'View'.
      final Size size = View.of(context).physicalSize;
                        ^^^^
Target kernel_snapshot failed: Exception

**Comment by SanskarModi22** [comment]
In that case, you can replace View with MediaQuery and use the size property to get the physical size of the screen.
