### ISSUE TITLE
using callTap() with DropdownButtonFormField2

### ISSUE THREAD

**Issue by martinWaldenburger** [AhmedLSayed9/dropdown_button2#147]
Hello,
how can I use the function callTap() with the DropdownButtonFormField2?

It works fine with the DropdownButton2 as described here: https://github.com/AhmedLSayed9/dropdown_button2/issues/33 

In the Code of the dropwdown_button2 (line 1835) it is described that you can set the key of the DropdownButton2 child widget, but I can't get it working.

I would be very grateful if someone could give me some assistance.

**Comment by AhmedLSayed9** [comment]
Use `dropdownButtonKey` parameter when using `DropdownButtonFormField2`
