### ISSUE TITLE
Search Issue in when installing app in real device

### ISSUE THREAD

**Issue by altafShaikh1717** [AhmedLSayed9/dropdown_button2#149]
Can Anyone Help me with the issue,

When I am using emulator / debugging in real device search is working but once I am generating APK and installing device search is not working.

**Comment by AhmedLSayed9** [comment]
Can you provide a working sample that produces the issue?

**Comment by altafShaikh1717** [comment]
I have replicated the case in below public repository 

[my_app](https://github.com/altafShaikh1717/dropdown2issue)

**Comment by AhmedLSayed9** [comment]
What's the issue here and the steps to produce it?

**Comment by altafShaikh1717** [comment]
When I run the app in emulator it will search value in drop down, but when I am generating APK search is not working

**Comment by altafShaikh1717** [comment]
I have try to print the search parameter 


                searchMatchFn: (rtItem, searchValue) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text(rtItem.child.toString()),
                      backgroundColor: Theme.of(context).errorColor,
                    ),
                  );
                  return (rtItem.child
                      .toString()
                      .toLowerCase()
                      .contains(searchValue.toLowerCase()));
                },
              ),

Scaffold is printing **Widget** only

**Comment by altafShaikh1717** [comment]
![ba845263-6f6c-4021-b4e3-5b1dbd32edcd](https://github.com/AhmedLSayed9/dropdown_button2/assets/12778262/aea1bbae-979f-438e-9b3a-da7c1f42dbc2)

**Comment by AhmedLSayed9** [comment]
Well, your code doesn't compile anyway.

You need to define a generic type of the items for your `DropdownButtonFormField2`. This is necessary so that `searchMatchFn` can recognize the type of your items:
```dart
DropdownButtonFormField2<String>(
...
)
```

Secondly, you're not using `searchMatchFn` properly. You need to compare `rtItem.value` not `rtItem.child`. Your `value` here is the `id`, so either you use `DropDownItem` as your item (it needs to be equatable first) or access the item name by the id as following:
```dart
searchMatchFn: (rtItem, searchValue) {
  return (_locddl
      .firstWhere((e) => e.id == rtItem.value)
      .name
      .toLowerCase()
      .contains(searchValue.toLowerCase()));
},
```

**Comment by altafShaikh1717** [comment]
Thanks I realized mistake in search function, changed the code in and working.

Thanks a lot.
