### ISSUE TITLE
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by scuti-dai** [AhmedLSayed9/dropdown_button2#151]
![Screenshot 2023-06-07 at 11 44 21](https://github.com/AhmedLSayed9/dropdown_button2/assets/104118833/ae43af7a-6da3-4eb7-a9b7-9c385e0ac210)

![Screenshot 2023-06-07 at 11 44 50](https://github.com/AhmedLSayed9/dropdown_button2/assets/104118833/9707c69e-fcf5-4665-9935-08fecb4e5827)

I just add library and use, when i reload screen, this error is showing.

**Comment by AhmedLSayed9** [comment]
Without an additional information I can't help with this.
Feel free to ask for re-open if you have more information.
