### ISSUE TITLE
Bottom line doesn't change color when is focused in desktop application.

### ISSUE THREAD

**Issue by claudiobsi** [AhmedLSayed9/dropdown_button2#152]
How can I change the bottom border color when widget is focused like image below? In a desktop application(windows).
![image](https://github.com/AhmedLSayed9/dropdown_button2/assets/39312079/c47131cc-9834-44cb-a837-ea9b3e4f4a2f)
In this image I am using [DropdownButtonFormField](https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html), but in DropdownButtonFormField2 doesn't work.

**Comment by AhmedLSayed9** [comment]
Can you provide an example using [DropdownButtonFormField](https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html) ?

**Comment by claudiobsi** [comment]
`
import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyHomePage(title: "DropDownButton Sample",));
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: SafeArea(
            child: Form(
              child: SizedBox(
                width: 200,
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    DropdownButtonFormField(
                      items: _getItems(),
                      onChanged: (_) {},
                    ),
                    const Divider(),
                    DropdownButtonFormField(
                      items: _getItems(),
                      onChanged: (_) {},
                    ),
                    DropdownButtonFormField2(
                      items: _getItems(),
                      onChanged: (_) {},
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  List<DropdownMenuItem<String>> _getItems() {
    return ["Option 1", "Option 2"]
        .map<DropdownMenuItem<String>>((String value) {
      return DropdownMenuItem<String>(
        value: value,
        child: Text(value),
      );
    }).toList();
  }
}
`

**Comment by AhmedLSayed9** [comment]
I added some offset so you can observe the focus color, it works fine:

https://github.com/AhmedLSayed9/dropdown_button2/assets/70890146/f9526eb9-44ed-469c-a341-b317ebbdc2f9

or you mean it doesn't stay highlighted after selecting an option?

**Comment by AhmedLSayed9** [comment]
However, the dropdown menu is stealing the focus from the underlying button which is an open flutter [issue](https://github.com/flutter/flutter/issues/106923).
I'll push a temporary solution for it so that the button maintain focused properly when menu open and unfocus when it's closed.

**Comment by claudiobsi** [comment]
> I added some offset so you can observe the focus color, it works fine:
> Screen.Recording.2023-06-17.at.4.45.00.AM.mov
> 
> or you mean it doesn't stay highlighted after selecting an option?

Thanks for fast reply.

I meant when using the TAB key to navigate between widgets.

https://github.com/AhmedLSayed9/dropdown_button2/assets/39312079/346af6df-0ffa-45e9-b3fa-a46fdacb855c

**Comment by AhmedLSayed9** [comment]
Check [`DropdownButtonFormField2`](https://github.com/AhmedLSayed9/dropdown_button2#7-using-dropdownbuttonformfield2-with-form). You should set `isDense: true,` and `contentPadding: EdgeInsets.zero,`.

**Comment by AhmedLSayed9** [comment]
wait, focus border is not highlighted, let me check

**Comment by AhmedLSayed9** [comment]
Nvm, I'll fix it soon

**Comment by AhmedLSayed9** [comment]
Also, the behavior of increasing height/width through button data and setting `isDense: true,` and `contentPadding: EdgeInsets.zero` may not be needed anymore.
