### ISSUE TITLE
Error: unable to find directory entry in pubspec.yaml

### ISSUE THREAD

**Issue by tomk9** [AhmedLSayed9/dropdown_button2#153]
Commands `flutter run` and `flutter test` shows the error:
`Error: unable to find directory entry in pubspec.yaml: /Users/tomasz/.pub-cache/hosted/pub.dev/dropdown_button2-2.2.4/assets/images/`

**Comment by AhmedLSayed9** [comment]
Ops sorry, I'll fix it.

**Comment by AhmedLSayed9** [comment]
There were some conflicts with `.pubignore`. It should work fine now.
