### ISSUE TITLE
Setting scrollbarTheme doesn’t work

### ISSUE THREAD

**Issue by blakewood84** [AhmedLSayed9/dropdown_button2#154]
Hey guys when setting `scrollbarTheme` data in the `DropdownStyle` class nothing seems to work.

Im wanted the scroll bar to always appear if it’s scrollable so the user knows there more menu items.

I’ve set `trackVisibility` to `true` as well as `thumbVisibility`. No luck.

I’ve even wrapped `DropdownButton2` with Theme and tried that way as well.

thanks for any help!

**Comment by AhmedLSayed9** [comment]
Can you provide a working sample that produces the issue?

**Comment by blakewood84** [comment]
> Can you provide a working sample that produces the issue?

Sure:

```dart
Expanded(
  child: DropdownButtonHideUnderline(
    child: DropdownButton2(
      isExpanded: true,
      value: null,
      hint: const Text(
        'Select a Project',
      ),
      items: const [
        DropdownMenuItem(
          value: 'Emanate',
          child: Text(
            'Emanate',
          ),
        ),
        DropdownMenuItem(
          value: 'Drop',
          child: Text(
            'Drop',
          ),
        ),
        DropdownMenuItem(
          value: 'Test2',
          child: Text(
            'Test2',
          ),
        ),
        DropdownMenuItem(
          value: 'Test3',
          child: Text(
            'Test3',
          ),
        ),
        DropdownMenuItem(
          value: 'Test4',
          child: Text(
            'Test4',
          ),
        ),
        DropdownMenuItem(
          value: 'Test5',
          child: Text(
            'Test5',
          ),
        ),
        DropdownMenuItem(
          value: 'Test6',
          child: Text(
            'Test6',
          ),
        ),
      ],
      style: const TextStyle(
        fontSize: 14,
        color: Colors.black,
      ),
      buttonStyleData: ButtonStyleData(
        padding: const EdgeInsets.only(right: 10),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(4),
          border: Border.all(
            color: Colors.black26,
          ),
        ),
      ),
      menuItemStyleData: const MenuItemStyleData(
        padding: EdgeInsets.only(left: 10, right: 10),
      ),
      dropdownStyleData: const DropdownStyleData(
        offset: Offset(0, -2),
        maxHeight: 200,
        scrollbarTheme: ScrollbarThemeData(
          thumbVisibility: MaterialStatePropertyAll(true),
          trackVisibility: MaterialStatePropertyAll(true),
          thumbColor: MaterialStatePropertyAll(Colors.red),
          trackColor: MaterialStatePropertyAll(Colors.red),
        ),
        padding: EdgeInsets.only(left: 10, right: 10),
        // padding: const EdgeInsets.only(left: 10, right: 10),
      ),
      iconStyleData: const IconStyleData(
        icon: Icon(
          Icons.unfold_more,
          color: Colors.black26,
          size: 20,
        ),
      ),
      onChanged: (value) {},
    ),
  ),
),
```

As you can see I've set `trackVisibility` to `true` as well as `thumbVisibility`:

![Screen Shot 2023-06-22 at 11 47 41 AM](https://github.com/AhmedLSayed9/dropdown_button2/assets/60270366/a78619a9-f7ee-42ee-a60f-02e6735164e3)

I've also set the thumb and track color to red. It doesn't do anything to the track styling at all when I actually scroll:

![Screen Shot 2023-06-22 at 11 48 22 AM](https://github.com/AhmedLSayed9/dropdown_button2/assets/60270366/7b9c9402-bfd9-43c0-a5ee-87bfc5b7cace)

**Comment by AhmedLSayed9** [comment]
It's working fine for me. What are you running this on?

**Comment by blakewood84** [comment]
@AhmedLSayed9 using `iphone14 Simulator with IOS 16.1`.

![Screen Shot 2023-06-22 at 11 59 41 AM](https://github.com/AhmedLSayed9/dropdown_button2/assets/60270366/f054dc57-6d36-4065-b881-e8bd323bb9ff)

**Comment by AhmedLSayed9** [comment]
This is related to flutter. The overridden `scrollbarTheme` at `Theme.of(context)` does apply for MaterialScrollbar but not for CupertinoScrollbar (related to https://github.com/flutter/flutter/issues/99013).

We'll have to pass `scrollbarTheme` manually then to make this work.

Also, `thumbVisibility` should be true by default.

**Comment by blakewood84** [comment]
@AhmedLSayed9 thanks for the prompt turn around. I will check the update. Blessings.
