### ISSUE TITLE
openMenuIcon bug and unable to update to the newest version because of shared_preferences 

### ISSUE THREAD

**Issue by vasp3r** [AhmedLSayed9/dropdown_button2#155]
There is a bug when the icon does not change its state to the openMenuIcon when the menu is opened. It has been fixed (I think) in the version 2.0.0 ("Fix rebuild issue of openMenuIcon"). The thing is, I cannot upgrade the package to the version beyond 2.1.4 because shared_preferences restricts me to do so. Latest shared_preferences depends on file v6.0.0, and the latest releases of the dropdown_button2 use file v7.0.0.  I doubt the shared_preferences will be updated anytime soon, so is it really necessary to use the file v7.0.0 here? Or is there any other solution to deal with this issue?

> Because no versions of shared_preferences match >2.1.2 <3.0.0 and shared_preferences 2.1.2 depends on shared_preferences_windows ^2.2.0, shared_preferences ^2.1.2 requires shared_preferences_windows ^2.2.0.
And because no versions of shared_preferences_windows match >2.2.0 <3.0.0, shared_preferences ^2.1.2 requires shared_preferences_windows 2.2.0.
And because shared_preferences_windows 2.2.0 depends on file ^6.0.0 and dropdown_button2 >=2.2.0 depends on file ^7.0.0, shared_preferences ^2.1.2 is incompatible with dropdown_button2 >=2.2.0.

**Comment by AhmedLSayed9** [comment]
You can use 'dependency_overrides' in your pubspec.yaml file:
```
dependency_overrides:
  file: ^7.0.0
```
