### ISSUE TITLE
Avoid capturing focus when Dropdown is opened

### ISSUE THREAD

**Issue by Colton127** [AhmedLSayed9/dropdown_button2#156]
Opening the dropdown captures focus, closing any open keyboard. I'm using modal bottom sheet's that consist of a textfield and a dropdown box. By default, the textfield captures focus - user input is always required. However, if the dropdown box is tapped while the keyboard is opened, the keyboard closes, which creates a very annoying animation as the modal sheet lowers to the bottom of the page.

Here's what I have tried thus far:

```
Focus(
            autofocus: false,
            descendantsAreFocusable: false,
            descendantsAreTraversable: false,
child: ...DropdownButton2
```
Within DropdownButton2 itself:

`focusNode: FocusNode(canRequestFocus: false, descendantsAreFocusable: false),`

This is a minor inconvenience and I really appreciate the package. It has came in handy numerous times.

**Comment by AhmedLSayed9** [comment]
It's expected for dropdown button to take focus away from TextField.
I think what you're describing is the expected behavior or am i missing some point here?

**Comment by Colton127** [comment]
> It's expected for dropdown button to take focus away from TextField. I think what you're describing is the expected behavior or am i missing some point here?

Hi, thank you for the prompt response. It is indeed expected behavior that the dropdown menu captures focus and thus hides the keyboard. I just wanted an option to override this for better user experience. 

When the keyboard is temporarily hidden during onset of dropdown menu opened, the modal bottom sheet is pushed to the bottom of the screen. Once a selection is made in the dropdown menu, the keyboard re-appears, pushing the modal bottom sheet to the top. This is aggravating especially on larger devices. 

Because this isn't a problem, and is also expected behavior, I'm going to close this issue. I'll see if I can integrate a solution and if so do a pull request.

Thank you.
