### ISSUE TITLE
warning while expanding/reducing listview

### ISSUE THREAD

**Issue by manand-ipratico** [AhmedLSayed9/dropdown_button2#159]
When  expanding/reducing listview you got this warning:

D/GlobalPenUtil( 8802): handleGlobalPenEvent ACTION_UP  isPenView: false
D/GlobalPenUtil( 8802):  ViewRootImpl  handleGlobalPenEvent ACTION_UP is not PenView: 

Performance are decreased.

**Comment by AhmedLSayed9** [comment]
Hello, Can you provider more details?

**Comment by manand-ipratico** [comment]
HI, this is how i build my dropdown.

![WhatsApp Image 2023-06-30 at 14 33 37](https://github.com/AhmedLSayed9/dropdown_button2/assets/68277252/c07c89c4-2885-4662-aa05-674dafc2b16b)
![WhatsApp Image 2023-06-30 at 14 33 36](https://github.com/AhmedLSayed9/dropdown_button2/assets/68277252/20eb8d3b-f0ab-4c12-91c2-594aec8c3b61)

[myDropDown.zip](https://github.com/AhmedLSayed9/dropdown_button2/files/11916256/myDropDown.zip)

When i expand it o git the error i said. 
If you need more info ask them to me.

thank's in advance

**Comment by manand-ipratico** [comment]
sorry it was my fault
