### ISSUE TITLE
text group separator

### ISSUE THREAD

**Issue by ivanzhadnov** [AhmedLSayed9/dropdown_button2#160]
is it possible make add text group separator
<img width="352" alt="image (2)" src="https://github.com/AhmedLSayed9/dropdown_button2/assets/44845863/71bf9668-f196-4908-b540-f1652c1c93b1">

**Comment by AhmedLSayed9** [comment]
Check [3. DropdownButton2 with separator widgets like dividers](https://github.com/AhmedLSayed9/dropdown_button2/issues/160#3-dropdownbutton2-with-separator-widgets-like-dividers)
