### ISSUE TITLE
Apply BackdropFilter for dropdown menu - "frosted glass" style

### ISSUE THREAD

**Issue by alemazzo95** [AhmedLSayed9/dropdown_button2#161]
Hello,
I would like to apply a "frosted glass" effect to the dropdown menu, but I cannot find a way to customize the builder of it.
Is there a way to apply a BackdropFilter to the Container of the dropdown menu, achieving the kind of result shown in the screenshot below?

<img width="246" alt="Screenshot 2023-07-13 alle 12 13 42" src="https://github.com/AhmedLSayed9/dropdown_button2/assets/22558918/5dfbf443-fc2b-47b6-8717-defd2dd2f1c0">

**Comment by AhmedLSayed9** [comment]
You can now do:
```dart
dropdownStyleData: DropdownStyleData(
  elevation: 0,
  decoration: BoxDecoration(
    color: Colors.grey.shade200.withOpacity(0.5),
  ),
  dropdownBuilder: (ctx, child) {
    return ClipRRect(
      clipBehavior: Clip.antiAlias,
      child: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 10.0, sigmaY: 10.0),
        child: child,
      ),
    );
  },
),
```
