### ISSUE TITLE
Feature request/question: expand dropdown width to largest item child

### ISSUE THREAD

**Issue by rikbrown** [AhmedLSayed9/dropdown_button2#163]
As far as I can tell the `DropdownStyleData` only allows a fixed numeric width. I'd like this to be flexible and expand to the largest `DropdownMenuItem` child. Is this possible?

**Comment by rikbrown** [comment]
I actually saw your link to this package in this SO question - https://stackoverflow.com/questions/70652668/flutter-width-of-dropdown-menu-independent-of-button-size - but it isn't exactly clear how to achieve this.

**Comment by AhmedLSayed9** [comment]
If both buttonWidth & dropdownWidth is null (or not used), their width will be calculated from the maximum width of items or hint text (dynamic width).

If you manually set buttonWidth then dropdown menu width will be equal to button's width. In that case, you can only use dropdownWidth to set different width to the menu but it can't be dynamic.

**Comment by rikbrown** [comment]
Ah, I see the issue. I am using a `customButton` which is inherently smaller than the contents of the dropdown. The dropdown appears to be sizing based on my custom button width, not its contents width.

>If you manually set buttonWidth then dropdown menu width will be equal to button's width. In that case, you can only use dropdownWidth to set different width to the menu but it can't be dynamic.

So as I understand, there's no way for the dropdown to size itself _dynamically_ based on its contents - it only sizes itself based on the button it's attached to.

**Comment by rikbrown** [comment]
<img width="141" alt="image" src="https://github.com/AhmedLSayed9/dropdown_button2/assets/2906188/ffd4d664-9dd7-453f-a7aa-b8f5b4cc4aa0">

to illustrate the problem w/ a smaller custom button.

**Comment by AhmedLSayed9** [comment]
> So as I understand, there's no way for the dropdown to size itself _dynamically_ based on its contents - it only sizes itself based on the button it's attached to.

"If both buttonWidth & dropdownWidth is null (or not used), their width will be calculated from the maximum width of items or hint text (dynamic width)."
As said, the only way is to not set button and dropdown menu widths  :)

You can however set `isExpanded = true` to avoid the overflow.

**Comment by rikbrown** [comment]
My custom button  is a `FilledButton` in the above case - so it controls its own width based on the text in it, which is both custom and uses a smaller font. So I'm not setting its width per-se, but neither is DropdownButton2? Setting `isExpanded` doesn't seem to change the behaviour for me.

_as an aside: This probably isn't the best way to be using a FilledButton as the customButton because I had to use [some magic](https://stackoverflow.com/questions/57529394/how-to-open-dropdownbutton-when-other-widget-is-tapped-in-flutter) to open the dropdown because its `onPressed` overrode the dropdown's._

```dart
return DropdownButtonHideUnderline(
        child: DropdownButton2<String>(
      isExpanded: true,
      key: ddKey,
      items: children,
      value: items.firstOrNull,
      onChanged: (value) {},
      dropdownStyleData: const DropdownStyleData(width: null),
      customButton: FilledButton.icon(
          onPressed: openDropdown, label: child, icon: const FaIcon(FontAwesomeIcons.caretDown, size: 14)),
    ));
```

where `children` are basically instances of the below (similar to your checkbox example):
```
InkWell(
      onTap: onTap,
      child: Row(
        children: [
          if (selected) const Icon(Icons.check_box_outlined) else const Icon(Icons.check_box_outline_blank),
          const SizedBox(width: 16),
          child, // some text
        ],
      ),
    );
```

Thanks for helping me/telling me I'm doing this all wrong. Really like your package.

**Comment by AhmedLSayed9** [comment]
`isExpanded` should work. You need to wrap the text in that Row with `Expanded` too.

**Comment by rikbrown** [comment]
Gets rid of the error, but doesn't actually expand the dropdown:

<img width="104" alt="image" src="https://github.com/AhmedLSayed9/dropdown_button2/assets/2906188/d3fc1e92-001b-489a-b76e-2f13d712f7ca">

```dart
InkWell(
      onTap: onTap,
      child: Row(
        children: [
          if (selected) const Icon(Icons.check_box_outlined) else const Icon(Icons.check_box_outline_blank),
          const SizedBox(width: 16),
          Expanded(child: child),
        ],
      ),
    );
```

**Comment by AhmedLSayed9** [comment]
Yes, it shouldn't expand the dropdown. I was just talking about avoiding the overflow.

You can now set different width for the dropdown menu and let the text show on multiple lines or use some other overflow behavior as `TextOverflow.ellipsis` with `maxLines: 1` to maintain single line.

**Comment by rikbrown** [comment]
Understood. In my case I do want the dropdown to expand (otherwise there won't be very much visible at all) - is that a valid feature request?

In the meantime I used some more [magic](https://stackoverflow.com/a/74701386/2219288) to measure the size of the children and find the largest and set that as the width. Probably not super performant but works.

**Comment by AhmedLSayed9** [comment]
It's not possible (unless we measure the size of children as your workaround but that's ofc not performance-wise to be implemented internally in the package).

The dropdown menu is a `ListView` and you can't make ListView's width fits its content.

The tricky part of the dynamic width behavior when not setting both (buttonWidth & dropdownWidth) is that dropdown menu items are initially loaded using `IndexedStack` that matches the button width, and later the menu can use that width (button width). And therefore, when the buttonWidth is not set, it will take the maximum width of items (or hint text) as it's been rendered using `IndexedStack`, and Voila! both button and menu can take the max width of items. This can't happen if the button doesn't take dynamic width too `the items width`.

**Comment by rikbrown** [comment]
Thanks - your explanation makes sense, even if it’s a shame for my use case. I’d mark it the accepted answer if this was StackOverflow :)

I’ll stick with my size measuring hack for now and monitor the perf impact and refactor the design if it’s a no go.

Thanks again for the answers and your work.
