### ISSUE TITLE
Dropdown does not open properly on web project viewed on mobile device (iOS + Safari / Mozilla)

### ISSUE THREAD

**Issue by metafounder** [AhmedLSayed9/dropdown_button2#168]
When running a web project in release mode on mobile device iOS (Safari, and Mozilla tried so far) instead of opening the dropdown, a grey box appears instead. 

This has something to do with dart to js conversion I think. 

```
Flutter version 3.10.5  
Dart version 3.0.5
```

This started happing after updating the dropdown_button2 version from:  ^2.1.4 to ^2.3.6

**Comment by metafounder** [comment]
update: on Android devices seems to work ok. The error is only for iOS devices.

**Comment by metafounder** [comment]
up, does anyone else have this problem ?

**Comment by metafounder** [comment]
I can try to fix this myself, however, can anyone offer a pointer or a starting point?

**Comment by AhmedLSayed9** [comment]
Do you have any further information or steps to reproduce the issue?

**Comment by metafounder** [comment]
steps to reproduce the issue: 

1. create a simple dropdown_button2 `^2.3.7` for a flutter web 
2. build for release with flutter `3.10.5` and deploy the project on a custom domain from where it can be accessible (!)
3. then try to open the dropdown from the released project on a real physical mobile iOS device from Safari (on Android it works, so it has to be iOS). Desktop is also ok, iOS & Windows. 

Please note that by "release" -> I mean actually deploying the project on a publically accessible domain from where it can be accessible from browsers.


Yeah I know, replicating is not gonna be easy, but there is no one piece of code I can give to you that can be self-sufficient to replicate the issue. Reproducing the issue, in this case, is complicated as it involves a proper release and a real physical iOS device. 

Here's a real picture of the issue in the wild: 


![365531508_305864515304068_3385111005447516775_n](https://github.com/AhmedLSayed9/dropdown_button2/assets/25162264/2b137683-b5ab-445e-a88d-3063626674af)

I find it strange that other people do not have this issue.

**Comment by metafounder** [comment]
"I find it strange that other people do not have this issue." - or maybe they don't know they have it, as you can imagine this is not the kind of issue that the tests will catch.

**Comment by metafounder** [comment]
update: after the upgrade flutter to `3.13.0` the problem went away.

**Comment by AhmedLSayed9** [comment]
Great!
Tbh, I'd have needed time to test this in release mode on mobile web browser :)
