### ISSUE TITLE
Exception caught by widgets library 

### ISSUE THREAD

**Issue by alireza-hnzpv** [AhmedLSayed9/dropdown_button2#169]
dropdown_button2: ^2.3.6
hello.
i want connect 3 dropdown_button2s togetter.
second one related to first one.
second one related to threid one.

so. when i complate 3 filed it's good.
but when i change second one i got an error.

======== Exception caught by widgets library =======================================================
The following assertion was thrown building DropDownButtonFiled(state: _DropDownButtonFiledState#fdb1b):
There should be exactly one item with [DropdownButton]'s value: 141. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:dropdown_button2/src/dropdown_button2.dart':
Failed assertion: line 1742 pos 11: 'items == null ||
              items.isEmpty ||
              value == null ||
              items.where((DropdownMenuItem<T> item) {
                    return item.value == value;
                  }).length ==
                  1'

The relevant error-causing widget was: 
  DropDownButtonFiled DropDownButtonFiled:file:///Users/masoumi/Desktop/prospergroups/projects/flutter/abborhan/lib/pages/din_8074.dart:108:19
When the exception was thrown, this was the stack: 
#2      new DropdownButtonFormField2 (package:dropdown_button2/src/dropdown_button2.dart:1742:11)
#3      _DropDownButtonFiledState.build (package:ab_borhan/views/fileds/drop_down_buttons/drop_down_button.dart:79:14)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#8      StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6093:32)
#11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595:17)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#15     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#18     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#20     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#25     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#46     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#52     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#62     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#67     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#72     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#76     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#80     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#86     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#90     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#93     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#94     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#98     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#100    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6093:32)
#101    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595:17)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#105    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#108    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#109    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#110    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#113    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#115    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#119    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#122    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#124    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#130    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#132    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#135    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#137    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#140    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#142    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#146    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#150    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#154    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#157    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#159    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#163    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#166    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#168    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274:5)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#171    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#172    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#174    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442:14)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#177    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#178    StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
#181    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#182    Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#183    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#184    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#185    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#186    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#187    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#188    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#189    _invoke (dart:ui/hooks.dart:142:13)
#190    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#191    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

**Comment by alireza-hnzpv** [comment]
```
import 'package:ab_borhan/constant/colors.dart';
import 'package:ab_borhan/constant/files.dart';
import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../text/text_input.dart';
import '../../text/text_label_small.dart';


class DropDownButtonFiled extends StatefulWidget {
  final List<Map<String, Object?>> items;
  final String label;
  final String hint;
  final dynamic selectedValue;
  final String idValue;
  final String nameValue;
  final String error;
  final Function(dynamic value) onChange;

  const DropDownButtonFiled(this.items, {super.key, required this.label, required this.hint, required this.error, required this.onChange, required this.nameValue, required this.idValue,required this.selectedValue});

  @override
  State<StatefulWidget> createState()=>_DropDownButtonFiledState();
}

class _DropDownButtonFiledState extends State<DropDownButtonFiled> {

  dynamic selectedValue = null;

  List<DropdownMenuItem> _addDividersAfterItems(List<Map<String, Object?>> items) {
    final List<DropdownMenuItem> menuItems = [];
    for (final Map<String, Object?> item in items) {
      menuItems.addAll(
        [
          DropdownMenuItem(
            value: item[widget.idValue],
            child: Center(
              child: TextLabelSmall(item[widget.nameValue].toString()),
            ),
          ),
          if (item != items.last)
            const DropdownMenuItem<Map<String, Object?>>(
              enabled: false,
              child: SizedBox(
                child: Divider(),
              ),
            ),
        ],
      );
    }
    return menuItems;
  }

  List<double> _getCustomItemsHeights() {
    final List<double> itemsHeights = [];
    for (int i = 0; i < (widget.items.length * 2) - 1; i++) {
      if (i.isEven) {
        itemsHeights.add(40);
      }
      if (i.isOdd) {
        itemsHeights.add(4);
      }
    }
    return itemsHeights;
  }

  @override
  void initState() {
    setState(() {
      selectedValue = selectedValue;
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(10),
      child: DropdownButtonFormField2<dynamic>(
        value: selectedValue,
        isExpanded: false,
        decoration: InputDecoration(
          fillColor: Colors.red,
          errorStyle: const TextStyle(color: errorColor),
          enabledBorder: OutlineInputBorder(borderSide: const BorderSide(color: blueTwo), borderRadius:BorderRadius.circular(16)),
          focusedBorder: OutlineInputBorder(borderSide: const BorderSide(color: blueOne), borderRadius:BorderRadius.circular(16)),
          focusedErrorBorder: OutlineInputBorder(borderSide: const BorderSide(color: errorColor), borderRadius:BorderRadius.circular(16)),
          errorBorder: OutlineInputBorder(borderSide: const BorderSide(color: errorColor), borderRadius:BorderRadius.circular(16)),
          labelText: widget.label,
          labelStyle: Get.theme.textTheme.labelMedium,
          alignLabelWithHint: true,
        ),
        hint: TextInputFiled(widget.hint),
        items: _addDividersAfterItems(widget.items),
        validator: (dynamic value) {
          if (value == null || value.toString().isEmpty) {
            return widget.error;
          }
          return null;
        },
        onChanged: (dynamic value) {
          setState(() => selectedValue = value);
          widget.onChange(selectedValue);
        },
        buttonStyleData: const ButtonStyleData(
          padding: EdgeInsets.only(left: 10),
        ),
        iconStyleData: IconStyleData(
          icon: Image.asset(AssetFile.IC_ARROW_DOWN),
          iconSize: 24,
        ),
        dropdownStyleData: DropdownStyleData(
          elevation: 0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: blueFour),
            color: backgroundLightColor
          ),
        ),
        menuItemStyleData: MenuItemStyleData(
          padding: const EdgeInsets.symmetric(horizontal: 10),
          customHeights: _getCustomItemsHeights(),
        ),
      ),
    );
  }
}
```



and 


```
                  DropDownButtonFiled(typePipeList,label: 'din8074_filed_type_of_pipe_label'.tr,hint: 'din8074_filed_type_of_pipe_hint'.tr,error: 'din8074_filed_type_of_pipe_error'.tr, onChange: (dynamic value) => _onChangeTypeOfPipeDropDownButton(value), idValue: 'name', nameValue: 'name', selectedValue: typeOfPipeValue),
                  DropDownButtonFiled(pressurePipeList,label: '${'din8074_filed_pressure_label'.tr} (${'sign_atm'.tr})',hint: 'din8074_filed_pressure_hint'.tr,error: 'din8074_filed_pressure_error'.tr, onChange: (dynamic value) => _onChangePressureDropDownButton(value), idValue: 'id', nameValue: 'name', selectedValue: pressureOfPipeValue),
                  DropDownButtonFiled(diameterPipeList,label: '${'din8074_filed_diameter_pipe_label'.tr} (${'sign_mm'.tr})',hint: 'din8074_filed_diameter_pipe_hint'.tr,error: 'din8074_filed_diameter_pipe_error'.tr,onChange: (dynamic value) => _onChangeDiameterOfPipeDropDownButton(value), idValue: 'id', nameValue: 'd', selectedValue: diameterOfPipeValue),
```

```

  String? typeOfPipeValue;
  int? pressureOfPipeValue;
  int? diameterOfPipeValue;


  List<Map<String, Object?>> typePipeList = [
    {'name' : 'PE63'},
    {'name' : 'PE80'},
    {'name' : 'PE100'},
  ];
  List<Map<String, Object?>> pressurePipeList = [];
  List<Map<String, Object?>> diameterPipeList = [];

  Future<void> _onChangeTypeOfPipeDropDownButton(dynamic value) async {
    typeOfPipeValue = value;
    pressureOfPipeValue = null;
    diameterOfPipeValue = null;
    pressurePipeList.clear();
    diameterPipeList.clear();
    for(Map<String, Object?> item in await din8074Database.getDin8074HeaderFetchAll()){
      pressurePipeList.add({'id' : item['id'], 'name' : item[value]});
    }
    setState(() {});
  }

  Future<void> _onChangePressureDropDownButton(int value) async {
    pressureOfPipeValue = value;
    diameterOfPipeValue = null;
    diameterPipeList.clear();
    for(Map<String, Object?> item in await din8074Database.getDin8074BodyFetchAll(value)){
      diameterPipeList.add({'id' : item['id'], 'd' : item['d']});
    }
    setState(() {});
  }

  Future<void> _onChangeDiameterOfPipeDropDownButton(int value) async {
    diameterOfPipeValue = value;
    setState(() {});
  }
```

**Comment by AhmedLSayed9** [comment]
Your first unformatted code got your issue mentioned at almost all the issues 😜
Can you format it? I'm not sure if that will fix the unintended mention but give it a try.

**Comment by AhmedLSayed9** [comment]
Without an additional information I can't help with this. Feel free to ask for re-open if you have further information.
