### ISSUE TITLE
Does this effect support it? After trying many attribute parameters, they couldn't be adjusted

### ISSUE THREAD

**Issue by songxing10000** [AhmedLSayed9/dropdown_button2#171]
default state|expand Status
------------ | -------------  
![Snipaste_2023-07-29_15-29-00](https://github.com/AhmedLSayed9/dropdown_button2/assets/10040131/d2170d05-4a59-4f5c-adb0-9a2c23f118ce) | ![Snipaste_2023-07-29_15-29-08](https://github.com/AhmedLSayed9/dropdown_button2/assets/10040131/3be4b5f9-1f32-4788-81ad-700f7dfe7e55)

**Comment by AhmedLSayed9** [comment]
I'm not sure what is the issue here. Can you elaborate more?

**Comment by songxing10000** [comment]
No problem, the boss asked for a different style. However, remember that the problem seems to be that the right arrow cannot be hidden, the width of the internal pop-up option is not easy to set, and the overall rounded corner after pop-up
