### ISSUE TITLE
any hint how I can hook up my own search?

### ISSUE THREAD

**Issue by uri-ravzin** [AhmedLSayed9/dropdown_button2#172]
scenario, when search executes, I need to go back to the server and come back with new set of items, without closing the dialog.

I have tried to assign the new results to `DropdownButton2.items` variable in build, but it seems that rebuild does not refresh the values.

anyone dealt with such problem or have any ideas and directions?

Thanks !

**Comment by AhmedLSayed9** [comment]
Currently, updating an open dropdown menu is not supported. But, you can check https://github.com/AhmedLSayed9/dropdown_button2/issues/101 for a workaround.

**Comment by uri-ravzin** [comment]
> Currently, updating an open dropdown menu is not supported. But, you can check #101 for a workaround.

Thanks !
this seems ok for a workaround 👍 

any plans to support this update properly?
I would be happy to contribute, if needed !

**Comment by AhmedLSayed9** [comment]
> any plans to support this update properly? I would be happy to contribute, if needed !

There's currently an open issue #111 that's related to this feature.
Of course, Feel free to contribute :)

**Comment by markosole** [comment]
Hi all, I am trying to figure out how to show "Add new" button if search returns false (or no items are loaded from api, does not matter). It turned out to be complicated and opening/closing dropdown isn't nicest experience. 

I've ended up (for now) with custom modal that has a listview and text input which simulates same functionality.

**Comment by AhmedLSayed9** [comment]
> Hi all, I am trying to figure out how to show "Add new" button if search returns false (or no items are loaded from api, does not matter). It turned out to be complicated and opening/closing dropdown isn't nicest experience.
> 
> I've ended up (for now) with custom modal that has a listview and text input which simulates same functionality. Have anyione found way to make Dropdown work?

You can use [noResultsWidget](https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/DropdownSearchData/noResultsWidget.html)

**Comment by markosole** [comment]
Thank you @AhmedLSayed9 but I don't see any refference to that class or widget. Source does not have any definition for it, and I am using latest version `dropdown_button2: ^2.3.9`.
It's like looking for a needle in a haystack. If you could share a bit more details that would helpfull.

**Comment by AhmedLSayed9** [comment]
> Thank you [@AhmedLSayed9](https://github.com/AhmedLSayed9) but I don't see any refference to that class or widget. Source does not have any definition for it, and I am using latest version `dropdown_button2: ^2.3.9`. It's like looking for a needle in a haystack. If you could share a bit more details that would helpfull.

You can migrate to the latest beta version `3.0.0-beta.21`, it's safe to be used.
