### ISSUE TITLE
Unnecessary Roboto-Regular font is included in the release app since v2.3.1

### ISSUE THREAD

**Issue by javer** [AhmedLSayed9/dropdown_button2#176]
After updating from [v2.2.2](https://github.com/AhmedLSayed9/dropdown_button2/releases/tag/v2.2.2) to [v2.3.1](https://github.com/AhmedLSayed9/dropdown_button2/releases/tag/v2.3.1) my release app started including `assets/fonts/Roboto-Regular.ttf` which is used only in tests, increasing size of the app, therefore it shouldn't be in the production release of the application:
```
Archive:  app-arm64-v8a-release.apk
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    3740  Defl:N     2424  35% 01-01-1981 01:01 3077d68b  assets/flutter_assets/fonts/MaterialIcons-Regular.otf
     912  Defl:N      561  39% 01-01-1981 01:01 e9bac81b  assets/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
  168260  Defl:N    88413  48% 01-01-1981 01:01 b255bb25  assets/flutter_assets/packages/dropdown_button2/assets/fonts/Roboto-Regular.ttf
       0  Defl:N        2   0% 01-01-1981 01:01 00000000  assets/flutter_assets/packages/dropdown_button2/assets/images/.gitkeep
```

The issue was introduced in the commit fe5b83a9fbeb6092ebeee3a638345b0b662d37d8

The same issue with unnecessary `assets/images/.gitkeep` file.

It seems that both files should be excluded from `.pubignore` and/or `pubspec.yaml`, because they are used only for testing purposes of the library itself, therefore shouldn't be presented in the applications which use the library.

**Comment by AhmedLSayed9** [comment]
We have to either move these tests in a separate package or use the default `Ahem` font.
