### ISSUE TITLE
Programmatically open the dropdown menu on double tap event 

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [AhmedLSayed9/dropdown_button2#178]
Is there any way to open the dropdown menu with a double tap programmatically, am having a scenario to open my dropdown programmatically with a double tap gesture, and am having another action with on tap gesture, kindly assist me to accomplish this requirement. With [this](https://github.com/AhmedLSayed9/dropdown_button2/issues/33), it opens with a tap gesture.

**Comment by AhmedLSayed9** [comment]
You can use `onDoubleTap` of `GestureDetector` to achieve the same.
