### ISSUE TITLE
reduce button height

### ISSUE THREAD

**Issue by nhh1500** [AhmedLSayed9/dropdown_button2#182]
How can I reduce the button height? I tried isDense = true , padding: EdgeInsets.all(0), and customButton to reduce the height, but none of them worked for my case. I still can see the dropdownButton is larger than my customButton.
``` dart
DropdownButtonHideUnderline(
              child: DropdownButtonFormField2(
            isDense: true,
            buttonStyleData: ButtonStyleData(padding: EdgeInsets.all(0)),
            menuItemStyleData: MenuItemStyleData(padding: EdgeInsets.all(0)),
            dropdownStyleData: DropdownStyleData(padding: EdgeInsets.all(0)),
            customButton: Container(
              height: 30,
              color: Colors.pink,
              child: Text(
                widget.model.type,
                style: TextStyle(
                  color: Colors.black,
                ),
              ),
            ),
```
<img width="145" alt="image" src="https://github.com/AhmedLSayed9/dropdown_button2/assets/61719708/a7c57989-c89c-4463-a9e2-d2d3c8b7d257">

**Comment by AhmedLSayed9** [comment]
Please upgrade to latest version and test this again.
Feel free to ask for re-open if it is not solved yet.
