### ISSUE TITLE
Custom Button Tabbing fails with assertion

### ISSUE THREAD

**Issue by SaltH2OFish** [AhmedLSayed9/dropdown_button2#184]
If you have multiple dropdown buttons that use custom buttons, you will encounter an error when you try to navigate within the dropdown list using the arrow keys after clicking or tabbing into it.

The error message is: "Failed assertion: line 1401 pos 12: '_dropdownRoute == null' is not true."

dropdown_button2: 2.3.9
Flutter: stable, 3.13.1

**Comment by AhmedLSayed9** [comment]
Can you provide a minimal sample that reproduce the issue?

**Comment by SaltH2OFish** [comment]
> Can you provide a minimal sample that reproduce the issue?

Sure thing AhmedLSayed9. 
I was able to reproduce it using sample: _DropdownButton2 with few styling and customization

But here is a sample that I crafted so it will be easier to reproduce:
` final List<String> items = [
    'Item1',
    'Item2',
    'Item3',
    'Item4',
    'Item5',
    'Item6',
    'Item7',
    'Item8',
  ];

  String? selected1Value;
  String? selected2Value;

  @override
  Widget build(BuildContext context) {
    return Scaffold(

      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,

          children: [
            // instructions to reproduce issue
            const Text('INSTRUCTIONS', style: TextStyle(fontWeight: FontWeight.bold)),
            const Text('1. From TextField hit tab key\r\n'
                '2. Next hit enter key to show dropdown list.\r\n'
                '3. hit arrow key down to navigate\r\n'
                '4. hit enter key to select item'),

            const SizedBox(height: 50),

            // initial focus text field so you can tab to a dropdown button
            const SizedBox(
                width: 500,
                child:
                TextField(
                  decoration: InputDecoration(
                      hintText: 'Text field has initial focus so you can tab to a dropdownbutton2'
                  ),
                  autofocus: true,
                )
            ),

            const SizedBox(height: 20),

            // Dropdown List 1
            DropdownButtonHideUnderline(
              child: DropdownButton2<String>(
                isExpanded: true,
                hint: const Row(
                  children: [
                    Icon(
                      Icons.list,
                      size: 16,
                      color: Colors.yellow,
                    ),
                    SizedBox(
                      width: 4,
                    ),
                    Expanded(
                      child: Text(
                        'Select Item 1',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ],
                ),
                items: items
                    .map((String item) => DropdownMenuItem<String>(
                  value: item,
                  child: Text(
                    item,
                    style: const TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ))
                    .toList(),
                value: selected1Value,
                onChanged: (value) {
                  setState(() {
                    selected1Value = value;
                  });
                },
                buttonStyleData: ButtonStyleData(
                  height: 50,
                  width: 160,
                  padding: const EdgeInsets.only(left: 14, right: 14),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(14),
                    border: Border.all(
                      color: Colors.black26,
                    ),
                    color: Colors.redAccent,
                  ),
                  elevation: 2,
                ),
                iconStyleData: const IconStyleData(
                  icon: Icon(
                    Icons.arrow_forward_ios_outlined,
                  ),
                  iconSize: 14,
                  iconEnabledColor: Colors.yellow,
                  iconDisabledColor: Colors.grey,
                ),
                dropdownStyleData: DropdownStyleData(
                  maxHeight: 200,
                  width: 200,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(14),
                    color: Colors.redAccent,
                  ),
                  offset: const Offset(-20, 0),
                  scrollbarTheme: ScrollbarThemeData(
                    radius: const Radius.circular(40),
                    thickness: MaterialStateProperty.all(6),
                    thumbVisibility: MaterialStateProperty.all(true),
                  ),
                ),
                menuItemStyleData: const MenuItemStyleData(
                  height: 40,
                  padding: EdgeInsets.only(left: 14, right: 14),
                ),
              ),
            ),

            const SizedBox(height: 20),

            // Dropdown List 2
            DropdownButtonHideUnderline(
              child: DropdownButton2<String>(
                isExpanded: true,
                hint: const Row(
                  children: [
                    Icon(
                      Icons.list,
                      size: 16,
                      color: Colors.yellow,
                    ),
                    SizedBox(
                      width: 4,
                    ),
                    Expanded(
                      child: Text(
                        'Select Item 2',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.bold,
                          color: Colors.white,
                        ),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ],
                ),
                items: items
                    .map((String item) => DropdownMenuItem<String>(
                  value: item,
                  child: Text(
                    item,
                    style: const TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ))
                    .toList(),
                value: selected2Value,
                onChanged: (value) {
                  setState(() {
                    selected2Value = value;
                  });
                },
                buttonStyleData: ButtonStyleData(
                  height: 50,
                  width: 160,
                  padding: const EdgeInsets.only(left: 14, right: 14),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(14),
                    border: Border.all(
                      color: Colors.black26,
                    ),
                    color: Colors.redAccent,
                  ),
                  elevation: 2,
                ),
                iconStyleData: const IconStyleData(
                  icon: Icon(
                    Icons.arrow_forward_ios_outlined,
                  ),
                  iconSize: 14,
                  iconEnabledColor: Colors.yellow,
                  iconDisabledColor: Colors.grey,
                ),
                dropdownStyleData: DropdownStyleData(
                  maxHeight: 200,
                  width: 200,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(14),
                    color: Colors.redAccent,
                  ),
                  offset: const Offset(-20, 0),
                  scrollbarTheme: ScrollbarThemeData(
                    radius: const Radius.circular(40),
                    thickness: MaterialStateProperty.all(6),
                    thumbVisibility: MaterialStateProperty.all(true),
                  ),
                ),
                menuItemStyleData: const MenuItemStyleData(
                  height: 40,
                  padding: EdgeInsets.only(left: 14, right: 14),
                ),
              ),
            ),
          ],
        )
      ),
    );
  }`

**Comment by AhmedLSayed9** [comment]
Well, I'm able to reproduce the issue with the simple example and with single dropdown.
Somehow the tab key doesn't move focus to the items. I'm investigating the issue.

**Comment by AhmedLSayed9** [comment]
I've found the issue. It'll be fixed soon.

**Comment by SaltH2OFish** [comment]
That's great! Thank you.
