### ISSUE TITLE
Unsupported operation: Cannot modify an unmodifiable list

### ISSUE THREAD

**Issue by zemingyu2023** [AhmedLSayed9/dropdown_button2#186]
if I use 'customHeights', it always has this error :Unsupported operation: Cannot modify an unmodifiable list
 my code : customHeights: [5, 30, 1, 30, 1, 30],  I added  dividers between items and header.

**Comment by AhmedLSayed9** [comment]
Can you provide a minimal sample that reproduce the issue?

**Comment by romanNakonechnyiYalanytis** [comment]
@zemingyu2023 I got the same issue recently, errors gone after changing from `customHeights: [5, 30, 1, 30, 1, 30]` to `customHeights: List<double>.from([5.0, 30.0, 1.0, 30.0, 1.0, 30.0])` in that case its not passed as unmodifiable list

**Comment by AhmedLSayed9** [comment]
Without further information and while there's a workaround, i'm closing this.
