### ISSUE TITLE
Border Radius on DropdownMenuItem

### ISSUE THREAD

**Issue by selsapingardi** [AhmedLSayed9/dropdown_button2#187]
Hi! I'm loving your package and have used it in multiple projects now. 😃

But I was wondering if you would add a way to customize the dropdown menu item's border radius. Since we can already customize the selected dropdown menu item, I added some padding and increased its border radius. But I realized that the dropdown menu item itself can't be styled in the same way. I've attached a screenshot of what my design looks like with the current package version below:

![file_2023-09-08_13 23 24](https://github.com/AhmedLSayed9/dropdown_button2/assets/73101677/8cd733c7-75a7-43fa-bb74-c8ce980fed5f)

As you can see from the image, the selected dropdown menu item (Full-Time) has a rounded border while the normal hovered dropdown menu item (Freelance) does not.

After some research into your package, I figured out that I had to add the `borderRadius` property in the `InkWell` widget of the `DropdownMenuItem`.

https://github.com/AhmedLSayed9/dropdown_button2/blob/f00a75c16608578c258d116b730642ad4109599f/lib/src/dropdown_button2.dart#L209-L219

So now the design looks as expected:

![file_2023-09-09_15 54 15](https://github.com/AhmedLSayed9/dropdown_button2/assets/73101677/7dcbb77b-aa0c-4e0c-94ab-378590d7edd5)

I'd be down to open a pull request to add the feature if you'd like! But if you have other ideas, feel free to let me know. 😄

Thank you!

**Comment by AhmedLSayed9** [comment]
Sounds good. Feel free to open a PR :)

**Comment by AhmedLSayed9** [comment]
This is available now at version 3.0.0-beta.2
