### ISSUE TITLE
Not run when apply CustomDropdownButton2 when run on web

### ISSUE THREAD

**Issue by khiemvu** [AhmedLSayed9/dropdown_button2#19]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building DropdownButton2<String>(dirty, state: _DropdownButton2State<String>#5ac76):
No Material widget found.

DropdownButton2<String> widgets require a Material widget ancestor.
In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter's material library, that material is represented by the Material widget. It is the Material widget that renders ink splashes, for instance. Because of this, many material library widgets require that there be a Material widget in the tree above them.

To introduce a Material widget, you can either directly include one, or use a widget that contains Material itself, such as a Card, Dialog, Drawer, or Scaffold.

**Comment by AhmedLSayed9** [comment]
Are you wrapping your widget with a Scaffold widget?

**Comment by khiemvu** [comment]
Thanks, i not wrapping in to Scaffold
