### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by mimranGLX** [AhmedLSayed9/dropdown_button2#190]
Here is my code, even its not printing the log into console. When i write anything in search field it shows the below error "D/InputMethodManager(28786): showSoftInput() view=io.flutter.embedding.android.FlutterView{4b88d49 VFE...... .F...... 0,0-1440,2904 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController(28786): show(ime(), fromIme=true)"

`DropdownButtonFormField2(
          alignment: Alignment.centerLeft,
          scrollbarAlwaysShow: true,
          dropdownOverButton: false,
          decoration: InputDecoration(
            focusedBorder: OutlineInputBorder(
              borderSide: const BorderSide(
                color: AppColors.primary,
              ),
              borderRadius: BorderRadius.circular(kBorderRadius8),
            ),
            enabledBorder: OutlineInputBorder(
              borderSide: const BorderSide(
                color: AppColors.generalTertiary,
              ),
              borderRadius: BorderRadius.circular(kBorderRadius8),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(kBorderRadius8),
              borderSide: const BorderSide(
                color: AppColors.generalTertiary,
              ),
            ),
            isDense: true,
            fillColor: AppColors.background,
            filled: true,
            contentPadding: widget.contentPadding ??
                EdgeInsets.only(
                    top: 14.h, bottom: 14.h, right: 16.w, left: 0.w),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(15),
            ),
          ),
          isExpanded: true,
          hint: widget.hintText,
          icon: widget.dropdownIcon ?? SvgPicture.asset(AppAssets.caretDown),
          iconEnabledColor: AppColors.generalPrimary,
          itemHeight: widget.itemHeight ?? kMinInteractiveDimension,
          dropdownPadding: widget.padding ?? EdgeInsets.zero,
          buttonHeight: widget.buttonHeight,
          dropdownMaxHeight: widget.dropdownMaxHeight,
          dropdownDecoration: BoxDecoration(
            borderRadius: BorderRadius.circular(8),
          ),
          selectedItemBuilder: widget.selectedItemBuilder != null
              ? (context) {
                  return [widget.selectedItemBuilder!];
                }
              : null,
          items: widget.items,
          dropdownScrollPadding: EdgeInsets.symmetric(vertical: 12.h),
          searchInnerWidgetHeight: 50,
          searchInnerWidget: Container(
            height: 50,
            padding: const EdgeInsets.only(
              top: 8,
              bottom: 4,
              right: 8,
              left: 8,
            ),
            child: TextFormField(
              expands: true,
              maxLines: null,
              controller: editingController,
              decoration: InputDecoration(
                isDense: true,
                contentPadding: const EdgeInsets.symmetric(
                  horizontal: 10,
                  vertical: 8,
                ),
                hintText: 'Search for an item...',
                hintStyle: const TextStyle(fontSize: 12),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
            ),
          ),
          searchMatchFn: (item, test) {
            log("search $test");
            return item.value.toString().contains(test);
          },
          //This to clear the search value when you close the menu
          onMenuStateChange: (isOpen) {
            if (!isOpen) {
              editingController.clear();
            }
          },
          validator: widget.validator,
          onChanged: widget.onChanged,
          onSaved: widget.onSaved,
          value: widget.value,
        ),`

**Comment by AhmedLSayed9** [comment]
Can you add a minimal working sample and format the code please?

**Comment by irving-dp** [comment]
in searchMatchFn try this code,
`item.value.toString().toLoweCase().contains(test.toLowerCase())`

**Comment by AhmedLSayed9** [comment]
In the lack of a reproducible sample, I'll close this.
