### ISSUE TITLE
How to stretch the tap target to fill the entire button

### ISSUE THREAD

**Issue by patrikbadanjak** [AhmedLSayed9/dropdown_button2#192]
How can I make the tap target larger like on the second image?

![small tap target](https://github.com/AhmedLSayed9/dropdown_button2/assets/48242978/1564815b-9bfa-4efb-bc60-e9d5371e8877)

![big tap target](https://github.com/AhmedLSayed9/dropdown_button2/assets/48242978/b55ed639-4183-4a94-af02-5d8a6350b83d)

**Comment by AhmedLSayed9** [comment]
Are you using latest version?

**Comment by patrikbadanjak** [comment]
I'm using the 2.1.4 because of some other dependencies

**Comment by AhmedLSayed9** [comment]
This has been fixed at recent releases.
The workaround for earlier versions is to adjust button height instead of add contentPadding.

**Comment by patrikbadanjak** [comment]
Which height?

**Comment by AhmedLSayed9** [comment]
@patrikbadanjak
https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/ButtonStyleData/height.html
It was called `buttonHeight` in earlier version.
