### ISSUE TITLE
i don't want to show selected item in list of dropdown. 

### ISSUE THREAD

**Issue by tjbaba2** [AhmedLSayed9/dropdown_button2#194]
i am using dropdownbutton2 but it requires 1 element for the selected value in items list, but i don't want to show selected item in list, and it i do that, it gives me error, how can in do this?

`dart
DropdownButtonHideUnderline(
        child: DropdownButton2<String>(
          isExpanded: true,
          iconStyleData: IconStyleData(
              icon: Icon(
            Icons.keyboard_arrow_down,
            color: theme.primaryColor,
          )),
          dropdownStyleData: DropdownStyleData(
            maxHeight: 250,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(5),
              color: theme.colorScheme.inversePrimary,
            ),
            elevation: 1,
            scrollbarTheme: ScrollbarThemeData(
              radius: const Radius.circular(20),
              thickness: MaterialStateProperty.all(6),
              thumbVisibility: MaterialStateProperty.all(true),
            ),
          ),
          hint: Text(
            'Select Item',
            style: TextStyle(
              fontSize: 14,
              color: Theme.of(context).hintColor,
            ),
          ),
          selectedItemBuilder: (context) {
            return items.map(
              (item) {
                return Padding(
                  padding: const EdgeInsets.symmetric(vertical: 5),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      hintText == null
                          ? const SizedBox.shrink()
                          : Text(
                              "$hintText",
                              style: TextStyle(
                                fontSize: 10,
                                color: Theme.of(context).unselectedWidgetColor,
                              ),
                            ),
                      Text(
                        val,
                        style: TextStyle(
                            overflow: TextOverflow.ellipsis,
                            fontSize: TextSizes.sm_md,
                            fontWeight: FontWeight.w500,
                            color: lightColorScheme.secondary),
                        maxLines: 1,
                      ),
                    ],
                  ),
                );
              },
            ).toList();
          },
          items: items.where((element) => element != val)
              .map((String item) => DropdownMenuItem<String>(
                    value: item,
                    child: Text(item,
                        style: TextStyle(
                            overflow: TextOverflow.ellipsis,
                            fontSize: 14,
                            fontWeight: FontWeight.w500,
                            color: lightColorScheme.secondary)),
                  ))
              .toList(),
          value: val,
          onChanged: (String? value) {
            onUpdate(value!);
          },
          buttonStyleData: const ButtonStyleData(
            padding: EdgeInsets.only(right: 15),
          ),
        ),
      ),

`

**Comment by AhmedLSayed9** [comment]
Can you properly format your code?

**Comment by tjbaba2** [comment]
```dart
DropdownButtonHideUnderline(
        child: DropdownButton2<String>(
          isExpanded: true,
          iconStyleData: IconStyleData(
              icon: Icon(
            Icons.keyboard_arrow_down,
            color: theme.primaryColor,
          )),
          dropdownStyleData: DropdownStyleData(
            maxHeight: 250,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(5),
              color: theme.colorScheme.inversePrimary,
            ),
            elevation: 1,
            scrollbarTheme: ScrollbarThemeData(
              radius: const Radius.circular(20),
              thickness: MaterialStateProperty.all(6),
              thumbVisibility: MaterialStateProperty.all(true),
            ),
          ),
          hint: Text(
            'Select Item',
            style: TextStyle(
              fontSize: 14,
              color: Theme.of(context).hintColor,
            ),
          ),
          selectedItemBuilder: (context) {
            return items.map(
              (item) {
                return Padding(
                  padding: const EdgeInsets.symmetric(vertical: 5),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      hintText == null
                          ? const SizedBox.shrink()
                          : Text(
                              "$hintText",
                              style: TextStyle(
                                fontSize: 10,
                                color: Theme.of(context).unselectedWidgetColor,
                              ),
                            ),
                      Text(
                        val,
                        style: TextStyle(
                            overflow: TextOverflow.ellipsis,
                            fontSize: TextSizes.sm_md,
                            fontWeight: FontWeight.w500,
                            color: lightColorScheme.secondary),
                        maxLines: 1,
                      ),
                    ],
                  ),
                );
              },
            ).toList();
          },
          items: items.where((element) => element != val)
              .map((String item) => DropdownMenuItem<String>(
                    value: item,
                    child: Text(item,
                        style: TextStyle(
                            overflow: TextOverflow.ellipsis,
                            fontSize: 14,
                            fontWeight: FontWeight.w500,
                            color: lightColorScheme.secondary)),
                  ))
              .toList(),
          value: val,
          onChanged: (String? value) {
            onUpdate(value!);
          },
          buttonStyleData: const ButtonStyleData(
            padding: EdgeInsets.only(right: 15),
          ),
        ),
      ),
```

**Comment by AhmedLSayed9** [comment]
Can you elaborate more what you want to do exactly?

**Comment by tjbaba2** [comment]
![WhatsApp Image 2023-09-21 at 6 05 51 PM](https://github.com/AhmedLSayed9/dropdown_button2/assets/133766877/2bc33946-897f-446a-a216-e1e665c4130a)
see this, i don't want it to show the item which is already selected in the dropdown list

**Comment by AhmedLSayed9** [comment]
You don't want to show it as button's text or at the dropdown list?

**Comment by tjbaba2** [comment]
i don't want to show it in the dropdown list, 
if a value is selected, then it shouldn't be in list

**Comment by AhmedLSayed9** [comment]
That's not supported due to how dropdown internally work and how the menu height is calculated.

A workaround is to use `dropdownSearchData`:
```dart
dropdownSearchData: DropdownSearchData(
            searchController: textEditingController,
            searchMatchFn: (item, _) {
              return item.value.toString() != selectedValue;
            },
          ),
```
