### ISSUE TITLE
Hover effect goes beyond DropdownButtonFormField2. Regression in 2.2.0.

### ISSUE THREAD

**Issue by TheLastFlame** [AhmedLSayed9/dropdown_button2#197]
After fixing bug #152 in 2.2.0, the bug from #56 has returned.

![image](https://github.com/AhmedLSayed9/dropdown_button2/assets/131446187/6a865b30-7087-46ca-a06a-219ce2ac9b2e)

**Comment by AhmedLSayed9** [comment]
Thanks for reporting this.
