### ISSUE TITLE
DropdownButtonFormField2 hover effect over hint and error

### ISSUE THREAD

**Issue by vasilich6107** [AhmedLSayed9/dropdown_button2#199]
When you add helper text to decorator or error the hover effect draws the shadow over them

<img width="451" alt="image" src="https://github.com/AhmedLSayed9/dropdown_button2/assets/6721286/888566e8-7eda-4e07-94c7-af1c05418f31">

**Comment by kstoykov** [comment]
I can confirm it. It is really annoying .
