### ISSUE TITLE
too many clicks for search

### ISSUE THREAD

**Issue by mauricev** [AhmedLSayed9/dropdown_button2#201]
To search, I first have to click into the dropdown and then click a second time into the search field before I can type anything. That makes no sense. Once I click, the dropdown should immediately respond to typing.

**Comment by AhmedLSayed9** [comment]
You can set `autofocus: true` at the TextFormField used for `searchBarWidget`.

**Comment by mauricev** [comment]
You mean like so
```
dropdownSearchData: DropdownSearchData(
          searchController: textEditingController,
          searchInnerWidgetHeight: 50,
          searchInnerWidget: Container(
            height: 50,
            padding: const EdgeInsets.only(
              top: 8,
              bottom: 4,
              right: 8,
              left: 8,
            ),
            child: TextFormField(
              autofocus: true,
```
If so, then it has no effect.

**Comment by AhmedLSayed9** [comment]
> You mean like so
> 
> ```
> dropdownSearchData: DropdownSearchData(
>           searchController: textEditingController,
>           searchInnerWidgetHeight: 50,
>           searchInnerWidget: Container(
>             height: 50,
>             padding: const EdgeInsets.only(
>               top: 8,
>               bottom: 4,
>               right: 8,
>               left: 8,
>             ),
>             child: TextFormField(
>               autofocus: true,
> ```
> 
> If so, then it has no effect.

It works fine at my side. Can you try using latest beta version?
If it still the same, provide a minimal sample that produces the issue.

**Comment by mauricev** [comment]
It does, in fact, work, in the beta version. Thanks.

By the way, it would be nice to see an option to make the edit field as part of the dropdown itself.
