### ISSUE TITLE
The new highlight behaviour #185 is incorrect for popup menus

### ISSUE THREAD

**Issue by alterhuman** [AhmedLSayed9/dropdown_button2#202]
It should be optional. #185 only works correctly for dropdowns, and even then a lot of people would not want that for dropdowns either.

**Comment by AhmedLSayed9** [comment]
That's expected when using `customButton`.
If you want to have the highlight behavior, you shouldn't use `customButton`.
Also, you can customize/disable the highlight behavior for dropdowns using `ButtonStyleData.overlayColor`
