### ISSUE TITLE
itemHeight intrinsic

### ISSUE THREAD

**Issue by Sotatek-QuanDo** [AhmedLSayed9/dropdown_button2#207]
Is there anyway I can let my DropDownMenuItem to be intrinsic? Like the default DropDownButton, the itemHeight auto scale when its content bigger. But in DropDownButton2, itemHeight seems to be fixed. I want it scale instead of calculate each item height in itemHeight list.

**Comment by AhmedLSayed9** [comment]
Check #173

> Like the default DropDownButton, the itemHeight auto scale when its content bigger.

IIRC, That's not true.

**Comment by Sotatek-QuanDo** [comment]
As i read in the docs

[itemHeight]
If null, then the menu item heights will vary according to each menu item's intrinsic height.

As you referenced, so the only way I can achieve this is by setting predefined menu height?

**Comment by AhmedLSayed9** [comment]
You're right. Explicitly set itemHeight to null will make its height dynamic.
The downside is that it'll break the scroll offset. I'll see what we can do.

**Comment by Sotatek-QuanDo** [comment]
Okay tks. At now my solution is:

  final span = TextSpan(text: yourText, style: yourStyle);
  final tp = TextPainter(text: span, textDirection: TextDirection.ltr);
  tp.layout(maxWidth: constraints.maxWidth);
  final numLines = tp.computeLineMetrics().length;

After I calculate numLines my text requires by the code above, if it > 1 then i will add biggerMenuHeight on my itemHeight list.
