### ISSUE TITLE
dropdown btn inside a dialog has problem

### ISSUE THREAD

**Issue by wenchaosong** [AhmedLSayed9/dropdown_button2#212]
**Version  2.3.9 and  3.0.0-beta.7**

**Bug info**

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
Navigator operation requested with a context that does not include a Navigator.

The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
packages/flutter/src/widgets/navigator.dart 2636:9                                <fn>
packages/flutter/src/widgets/navigator.dart 2642:14                               of
packages/dropdown_button2/src/dropdown_button2.dart 508:48                        [_handleTap]
packages/flutter/src/material/ink_well.dart 1154:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 275:24                              invokeCallback

**Problem**

as title say, use dropdown btn inside a dialog will cause this problem

**Comment by AhmedLSayed9** [comment]
Please provide a minimal working sample that produces the issue.

**Comment by wenchaosong** [comment]
~~~
import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/material.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';

class HomePage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => HomePageState();
}

class HomePageState extends State<HomePage> {
  final List<String> items = [
    'Item1',
    'Item2',
    'Item3',
    'Item4',
  ];
  String? selectedValue;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            SmartDialog.show(builder: (context) {
              return Container(
                height: 200,
                width: 200,
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(10),
                ),
                alignment: Alignment.center,
                child: _dropBtn(),
              );
            });
          },
          child: const Text('test'),
        ),
      ),
    );
  }

  Widget _dropBtn() {
    return DropdownButtonHideUnderline(
      child: DropdownButton2<String>(
        hint: Text(
          'Select Item',
          style: TextStyle(
            fontSize: 14,
            color: Theme.of(context).hintColor,
          ),
        ),
        items: items
            .map((String item) => DropdownMenuItem<String>(
                  value: item,
                  child: Text(
                    item,
                    style: const TextStyle(
                      fontSize: 14,
                    ),
                  ),
                ))
            .toList(),
        value: selectedValue,
        onChanged: (String? value) {
          setState(() {
            selectedValue = value;
          });
        },
        buttonStyleData: const ButtonStyleData(
          padding: EdgeInsets.symmetric(horizontal: 16),
          height: 40,
          width: 140,
        ),
        menuItemStyleData: const MenuItemStyleData(
          height: 40,
        ),
      ),
    );
  }
}
~~~

**Comment by wenchaosong** [comment]
I was use flutter_smart_dialog , but if use showDialog , it was ok

**Comment by AhmedLSayed9** [comment]
If you use Flutter's DropdownButton you'll get the same issue.
I'm closing this as it's related to `flutter_smart_dialog`.
