### ISSUE TITLE
The named parameter 'dropdownSeparator' isn't defined.

### ISSUE THREAD

**Issue by AntonLie** [AhmedLSayed9/dropdown_button2#222]
Hello,

how to add dropdownSeperator ?

 
Version:
dropdown_button2: ^2.3.9
  
  
### Screenshot
<img width="664" alt="Screenshot 2023-11-25 at 16 49 06" src="https://github.com/AhmedLSayed9/dropdown_button2/assets/89154283/4d1afad7-3d4f-4e60-b62a-411523894135">

Thank you

**Comment by hardgit** [comment]
dropdown_button2: ^3.0.0-beta.6

**Comment by AhmedLSayed9** [comment]
It has been introduced in the beta version.
