### ISSUE TITLE
searchData not working in release app (show grey blank dropdown container)    this code

### ISSUE THREAD

**Issue by sahaj-zibma** [AhmedLSayed9/dropdown_button2#226]
![d69d0f80-c536-40b4-8221-fb25d29210b9](https://github.com/AhmedLSayed9/dropdown_button2/assets/153197127/ae3e996a-19b5-431d-9690-ad95c46335d4)

DropdownButton2<String>(
                  iconStyleData: IconStyleData(
                      icon: Icon(DimenHelper.DROPDOWN_ICON),
                      iconSize: DimenHelper.DROPDOWN_ICON_SIZE),
                  buttonStyleData: const ButtonStyleData(height: 45),
                  dropdownStyleData: const DropdownStyleData(maxHeight: 300),
                  menuItemStyleData: const MenuItemStyleData(height: 45),
                  dropdownSearchData: DropdownSearchData(
                    searchController: _searchStaffController,
                    searchInnerWidgetHeight: 55,
                    searchInnerWidget: Container(
                      height: 55,
                      color: Colors.red,
                      padding: const EdgeInsets.only(
                          top: 8, bottom: 4, right: 8, left: 8),
                      child: TextFormField(
                        controller: _searchStaffController,
                        expands: true,
                        maxLines: null,
                        decoration: InputDecoration(
                          isDense: true,
                          contentPadding: const EdgeInsets.symmetric(
                              horizontal: 10, vertical: 10),
                          hintText: 'Search Staff',
                          hintStyle: const TextStyle(fontSize: 12),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8),
                          ),
                        ),
                      ),
                    ),
                    searchMatchFn: (item, searchValue) {
                      return item.child
                          .toString()
                          .substring(6, item.child.toString().length - 2)
                          .toLowerCase()
                          .contains(searchValue);
                    },
                  ),
                  onMenuStateChange: (isOpen) {
                    if (!isOpen) {
                      _searchStaffController.clear();
                    }
                  },
                  isExpanded: true,
                  style: TextStyle(
                      color: ColorHelper.textColor(isDark).withOpacity(.9),
                      fontWeight: FontWeight.w700),
                  underline: Container(height: 0),
                  onChanged: (String? newValue) {
                    setState(() {
                      staffDetailValue = newValue!;
                      debugPrint('Staff : $staffDetailValue');
                    });
                  },
                  value: staffDetailValue,
                  items: lstStaffDetailAPIItem,
                )

**Comment by irving-dp** [comment]
what the solution? I got this bug too, searching doesn't work in release mode but works in debug mode.
