### ISSUE TITLE
Failed assertion: line 991 pos 11 ... There shoiuld be exactly one item with DropdownButtons ...

### ISSUE THREAD

**Issue by gabriel-R-Lemes** [AhmedLSayed9/dropdown_button2#227]
I'm trying to  use a custom dropdownbutton2 widget, heres how he is:
// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:app_beneficiario/app/utils/colors.dart';
import 'package:dropdown_button2/dropdown_button2.dart';
import 'package:flutter/material.dart';

class CustomDropdownButton2 extends StatelessWidget {
  const CustomDropdownButton2({
    required this.hint,
    required this.value,
    required this.dropdownItems,
    required this.onChanged,
    this.selectedItemBuilder,
    this.hintAlignment,
    this.valueAlignment,
    this.buttonHeight,
    this.buttonWidth,
    this.buttonPadding,
    this.buttonDecoration,
    this.buttonElevation,
    this.icon,
    this.iconSize,
    this.iconEnabledColor,
    this.iconDisabledColor,
    this.itemHeight,
    this.itemPadding,
    this.dropdownHeight,
    this.dropdownWidth,
    this.dropdownPadding,
    this.dropdownDecoration,
    this.dropdownElevation,
    this.scrollbarRadius,
    this.scrollbarThickness,
    this.scrollbarAlwaysShow,
    this.offset = Offset.zero,
    super.key,
  });
  final String hint;
  final String? value;
  final List<DropdownMenuItem<String>> dropdownItems;
  final ValueChanged<String?>? onChanged;
  final DropdownButtonBuilder? selectedItemBuilder;
  final Alignment? hintAlignment;
  final Alignment? valueAlignment;
  final double? buttonHeight, buttonWidth;
  final EdgeInsetsGeometry? buttonPadding;
  final BoxDecoration? buttonDecoration;
  final int? buttonElevation;
  final Widget? icon;
  final double? iconSize;
  final Color? iconEnabledColor;
  final Color? iconDisabledColor;
  final double? itemHeight;
  final EdgeInsetsGeometry? itemPadding;
  final double? dropdownHeight, dropdownWidth;
  final EdgeInsetsGeometry? dropdownPadding;
  final BoxDecoration? dropdownDecoration;
  final int? dropdownElevation;
  final Radius? scrollbarRadius;
  final double? scrollbarThickness;
  final bool? scrollbarAlwaysShow;
  final Offset offset;

  @override
  Widget build(BuildContext context) {
    return DropdownButtonHideUnderline(
      child: DropdownButton2<String>(
        //To avoid long text overflowing.
        isExpanded: true,
        hint: Container(
          alignment: hintAlignment,
          child: Text(
            hint,
            overflow: TextOverflow.ellipsis,
            maxLines: 1,
            style: TextStyle(
              fontSize: 14,
              color: Theme.of(context).hintColor,
            ),
          ),
        ),
        value: value,
        items: dropdownItems,
        onChanged: onChanged,
        buttonStyleData: ButtonStyleData(
          height: 50,
          width: 320,
          padding: const EdgeInsets.symmetric(horizontal: 14),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(14),
            border: Border.all(
              color: darkPurple,
            ),
            color: offWhiteColor,
          ),
          elevation: 2,
        ),
        iconStyleData: const IconStyleData(
          icon: Icon(Icons.arrow_drop_down_rounded),
          iconSize: 40,
          iconEnabledColor: darkPurple,
          iconDisabledColor: darkPurple,
        ),
        dropdownStyleData: DropdownStyleData(
          maxHeight: 270,
          width: 320,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(14),
            color: darkPurple,
          ),
          offset: const Offset(0, 0),
          scrollbarTheme: const ScrollbarThemeData(
            radius: Radius.circular(40),
            thickness: MaterialStatePropertyAll(6),
            thumbVisibility: MaterialStatePropertyAll(true),
          ),
        ),
        menuItemStyleData: const MenuItemStyleData(
          height: 50,
          padding: EdgeInsets.symmetric(horizontal: 14),
        ),
      ),
    );
  }
}

And Heres how i call it:
CustomDropdownButton2(
  hint: 'Escolha a Especialidade',
  value: value1,
  dropdownItems: expertiseItens,
  onChanged: (value) {
    setState(() {
      value1 = value!;
      expertiseController.text = value;
    });
})

When i change value to expertiseItens.last.value, it works. but when i change the dropdown item, i does not change the value displayed...
What am i doing wrong?
Should i add more params to CustomDropdownButton2?

Heres the erro snippet:
![image](https://github.com/AhmedLSayed9/dropdown_button2/assets/108953357/639d9063-d69d-4580-a3b7-e4ca446ab2b9)

Thanks for all the help guys!

**Comment by soniasunil** [comment]
facing the same issue, as i am dynamically loading the values into items and due to the lag, it is throwing an error when i set the initial selected value as the items is empty at the time. Would be great if this could be fixed.

**Comment by AhmedLSayed9** [comment]
This mostly a bug in your code. I need a minimal sample that reproduces the issue.
