### ISSUE TITLE
Disable dropdown button

### ISSUE THREAD

**Issue by Daftus** [AhmedLSayed9/dropdown_button2#231]
Hi,

Am I missing something or is there an option for disabledHint but not option to disable the actual dropdown button ?

Thank you

**Comment by yeewan98** [comment]
Hi, I had encounter a problem that i have a initialize some value for the dropdown, i try to change the onchange to null, but how to change the initialize value color?

**Comment by Daftus** [comment]
@yeewan98 I'm not sure I understand your problem correctly, can you be more specific ? Thanks

**Comment by yeewan98** [comment]
@Daftus Thanks for reply. I found out the way to change the style of the initialize value for dropdown when the field is disable. Before that, when the field is disable, the text of the initialize value is still normal color which is black, then someone tell me can control the dropdownmenu item text style by adding validation to it, so it solve my problem
