### ISSUE TITLE
Accessing _isMenuOpen

### ISSUE THREAD

**Issue by JeanPSF** [AhmedLSayed9/dropdown_button2#24]
Goal:
I need to pass the _isMenuOpen attribute to my custom customButton.

Solution i found:
I use onTap/onMenuClose to set a state in my CustomDropdown widget (statefull), and i pass it to my customButton.

Sugestion:
Is there a better way to achieve this?
If not, is it possible to be acomplished with a single callback, that receives the actual _isMenuOpen value so i can ensure that my state and dropdown_button2 state are the same?

```
MyDropdown extends from stateful ....
isOpen = false;

`DropdownButtonFormField2(

isOpen: (value){
  setState((){
    isOpen = value;
  });
},
)
```
or

Changing the customButton from expecting a Widget to expecting a function that return a Widget and returns the _isMenuOpen as a parameter:
`customButton: (isOpen) => MyWidget(isOpen),`

**Comment by AhmedLSayed9** [comment]
You can achieve that using both onTap & onMenuClose, I don't see better scenario.
Can you share your both custom widgets so we can find best way to achieve this?

**Comment by JeanPSF** [comment]
This is my custom widget.
My concern about about the onTap & onMenuClose is that might exist (or might be implement in the future) a functionality/shortcut on opening/closing the dropdown, where those onTap & onMenuClose callbacks might not be used, which would unsync the real _isMenuOpen value from my own state, which i would like to avoid.
```
  Widget defaultSelectedItem(SphereDropdownOption<T> e) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          e.label ?? '',
          style: const TextStyle(
            backgroundColor: Colors.transparent,
            color: SystemColors.neutrals_50,
          ),
        ),
        Icon(
          isOpen ? VortexIcons.arrow_up : VortexIcons.arrow_down,
          size: 16,
          color: SystemColors.neutrals100,
        )
      ],
    );
  }
```

**Comment by AhmedLSayed9** [comment]
There's already `iconOnClick` parameter that show different icon when dropdown menu is open. I think that's what you're trying to achieve, right?

**Comment by JeanPSF** [comment]
> There's already `iconOnClick` parameter that show different icon when dropdown menu is open. I think that's what you're trying to achieve, right?

It does not work with customButtonn (and i think it should not).

**Comment by AhmedLSayed9** [comment]
Ah, I thought customButton is your own widget not the property in the package.
Let me think if we could make one callback for both onTap & onMenuClose.
