### ISSUE TITLE
DropDown button 2 latest beta fails with empty dropdown

### ISSUE THREAD

**Issue by vasilich6107** [AhmedLSayed9/dropdown_button2#244]
This code fails with 
```dart
DropdownButtonHideUnderline(
            child: DropdownButton2<String>(
              value: null,
              items: [],
            ),
          )
```

`RangeError (index): Invalid value: Valid value range is empty: 0`

`DropdownButton2State.build (package:dropdown_button2/src/dropdown_button2.dart:687:30)`

**Comment by FluffyDiscord** [comment]
I dont have this error, but it won't open nonetheless. I want it to open, because I am using `dropdownSearchData` and creating new items when nothing is found.

**Comment by AhmedLSayed9** [comment]
This no longer occurs in latest beta version.
Feel free to open a new issue if it still exists.

**Comment by AhmedLSayed9** [comment]
> ~I dont have this error~ (it does trigger when manually openening using `dropdownKey.currentState!.callTap()`), but it won't open nonetheless. I want it to open, because I am using `dropdownSearchData` and creating new items when nothing is found.

Let's discuss this at #257

**Comment by AhmedLSayed9** [comment]
> ~I dont have this error~ (it does trigger when manually openening using `dropdownKey.currentState!.callTap()`), but it won't open nonetheless. I want it to open, because I am using `dropdownSearchData` and creating new items when nothing is found.

Let's discuss this at #257
