### ISSUE TITLE
Can we keep value as well for beta version?

### ISSUE THREAD

**Issue by npateras** [AhmedLSayed9/dropdown_button2#249]
Hi, having a valueListenable is great, but I manage my own state with another state management dep and I want to be consistent so I want to also have the value option as well.

**Comment by AhmedLSayed9** [comment]
You can sync `valueListenable` with any external state using a listener or by updating it at `onChanged`.
Adding both `value` and `valueListenable` will complicate things.

**Comment by npateras** [comment]
> You can sync `valueListenable` with any external state using a listener or by updating it at `onChanged`. Adding both `value` and `valueListenable` will complicate things.

I see, that's understandable, I love dropdown2 and thanks for the swift reply 😁
