### ISSUE TITLE
Selecting a dropdownItem multiple times will trigger the WillPopScope time, resulting in a return to the previous page h

### ISSUE THREAD

**Issue by runkobe24** [AhmedLSayed9/dropdown_button2#25]
Selecting a dropdownItem multiple times will trigger the WillPopScope time, resulting in a return to the previous page

**Comment by runkobe24** [comment]
> 

Clicking the same dropdownitem multiple times will cause the page to go back to the previous page

**Comment by AhmedLSayed9** [comment]
I think this can't happen as the `removeDropdownRoute` method just dismiss `_dropdownRoute`. It doesn't call `navigator.pop()`.

Can you post a sample code clarify how this issue happen?

**Comment by AhmedLSayed9** [comment]
Closing this issue due to lack of information. Feel free to reopen with more details if you still have trouble.

**Comment by runkobe24** [comment]
> 我认为这不可能发生，因为`removeDropdownRoute`方法只是 dismiss `_dropdownRoute`。它不叫`navigator.pop()`。
> 
> 你能发布一个示例代码来澄清这个问题是如何发生的吗？


https://user-images.githubusercontent.com/23496409/164964549-d80ed990-6ab5-47f2-90ce-6c4979dbc295.mp4


@override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    final width = size.width;

    return Scaffold(
      appBar: AppBar(title: Text("select demo")),
      body: Stack(
        children: [
          CustomScrollView(
            slivers: <Widget>[
              // _buildBanner(),
              _selectMean(context, width),
              // _buildStickyBar(),
              // _buildList(),
            ],
          ),
        ],
      ),
    );
  }

Widget _selectMean(context, width) {
    return SliverToBoxAdapter(
      child: DropdownButtonHideUnderline(
        child: DropdownButtonFormField2(
          onTap: () {},
          offset: const Offset(10, 50),
          alignment: AlignmentDirectional.centerStart,
          // selectedItemHighlightColor: Colors.blue,
          dropdownWidth: width - 20.w,
          decoration: InputDecoration(
            isDense: true,
            contentPadding: EdgeInsets.zero,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(15),
            ),
          ),
          hint: const Text(
            'Choose Text',
            style: TextStyle(fontSize: 14, color: Colors.blue),
          ),
          icon: const Icon(
            Icons.arrow_drop_down,
            color: Colors.black45,
          ),
          iconSize: 30,
          buttonHeight: 60,
          buttonPadding: const EdgeInsets.only(left: 20, right: 10),
          dropdownDecoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(15),
            boxShadow: const [],
          ),
          items: items
              .map((item) => DropdownMenuItem<String>(
                    value: item,
                    child: Text(
                      item,
                      style: const TextStyle(fontSize: 14, color: Colors.red),
                    ),
                  ))
              .toList(),
          validator: (value) {
            if (value == null) {
              return 'Please select gender.';
            }
          },
          dropdownFullScreen: true,
          onChanged: (value) {},
          onSaved: (value) {
            selectedValue = value.toString();
          },
        ),
      ),
    );
  }
