### ISSUE TITLE
Very slow loading multiple dropdown buttons on one screen

### ISSUE THREAD

**Issue by kaciula** [AhmedLSayed9/dropdown_button2#252]
If I have a screen with 20 dropdown buttons, each with 50 elements, loading the screen takes a few seconds. I believe you are eagerly loading all menu lists at creation time.

The list of menu items should be loaded dynamically only when the dropdown menu is tapped. Also, ideally the menu list should not use shrinkWrap and load the extra items in the menu only when scrolling the list.

**Comment by AhmedLSayed9** [comment]
Can you check https://github.com/AhmedLSayed9/dropdown_button2/issues/196 and see if it helps?

**Comment by kaciula** [comment]
@AhmedLSayed9 I've now tried `^3.0.0-beta.11` but the performance is the same. You mention something about setting `buttonWidth` and `buttonHeight` but I cannot find them anywhere.


![Screenshot 2024-04-03 at 18 21 19](https://github.com/AhmedLSayed9/dropdown_button2/assets/18688/0a13f579-f2ab-4a8e-80ea-4fdf71ca10f5)

**Comment by AhmedLSayed9** [comment]
There's a [buttonStyleData](https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/ButtonStyleData-class.html) and it has a height and width.

**Comment by kaciula** [comment]
@AhmedLSayed9 Thank you very much. The UI is now much faster than before.
