### ISSUE TITLE
Allow closing dropdown programatically

### ISSUE THREAD

**Issue by FluffyDiscord** [AhmedLSayed9/dropdown_button2#256]
Right now we can only open the dropdown programaticaly using #33. I would like to close it programaticaly too.

**Comment by AhmedLSayed9** [comment]
I'll offer a better way to open/close dropdown menu instead of exposing `DropdownButton2State`

**Comment by AhmedLSayed9** [comment]
Wait, Why not using Navigator.pop ? @FluffyDiscord

**Comment by FluffyDiscord** [comment]
I had not think of that

**Comment by AhmedLSayed9** [comment]
I’ll update opening programmatically anyway, but there’s no need to add closing.

**Comment by AhmedLSayed9** [comment]
Opening menu programmatically has been updated and as closing menu can be achieved by Navigator.pop I'll close this.
