### ISSUE TITLE
Not possible to have label, text and dropdown values all aligned with OutlineInputBorder

### ISSUE THREAD

**Issue by giordy16** [AhmedLSayed9/dropdown_button2#265]
I want to implement a `DropdownButtonFormField2` with an `OutlineInputBorder` border. This is the code:

```
    return DropdownButtonFormField2(
      items: values.map<DropdownMenuItem>((entity) {
        return DropdownMenuItem(
          value: entity,
          child: Text(
            entity.toString(),
          ),
        );
      }).toList(),
      onChanged: (value) {
        if (onItemSelected != null) {
          onItemSelected!(value);
        }
      },
      decoration: InputDecoration(
        label: Text(title),
        labelStyle: TextStyle(color: theme.colorScheme.secondary),
        errorBorder: formErrorBorder(context),
        focusedBorder: formFocusedBorder(context),
        enabledBorder: formEnabledBorder(context),
        focusedErrorBorder: formFocusedBorder(context),
      ),
      validator: isMandatory ? mandatoryFieldDynamic() : null,
      value: initialValue,
    );
```

And this is the result:
![Screenshot 2024-05-06 at 16 57 32](https://github.com/AhmedLSayed9/dropdown_button2/assets/112980257/a29f7985-92a6-43b3-9038-dd33f018ac78)

I would like to have "Liquidità" (the selected value of the dropdown) to be aligned with the label on the border and the other dropdown values, but I am playing with the different paddings and I can't achieve what I want.

Any suggestions?

**Comment by AhmedLSayed9** [comment]
Check https://github.com/AhmedLSayed9/dropdown_button2/issues/237

**Comment by giordy16** [comment]
thank you, this helped https://stackoverflow.com/a/77971775/14036990
