### ISSUE TITLE
Default width error

### ISSUE THREAD

**Issue by ihorkozar** [AhmedLSayed9/dropdown_button2#28]
@AhmedLSayed9 Hello, I have a small question/remark. If you do not set the width of the button and dropdownlist, then the width of the button is taken as the maximum width of the child element from the list (correct me if I'm wrong). But at the same time, the dropdownlist has some paddings or margins (I did not find their variables) that are not added to this width. 

As a result, it turns out that this element does not completely fit into the dropdown and is cut off. If the list of items is static, then this is easily solved by setting specific sizes, but if the list for the dropdown comes from the server and can change, then a problem appears.

![Рисунок1](https://user-images.githubusercontent.com/45120893/166106252-ddcdd46b-c941-4215-abed-47cabba06edc.png)

**Comment by AhmedLSayed9** [comment]
Hello [ihorkozar](https://github.com/ihorkozar),

That's right. If you don't set buttonWidth or dropdownWidth, then the width of the button & menu is taken as the maximum width of the child element from the list or the hint text.

The padding that your dropdownlist has is the `itemPadding` which by default is `_kMenuItemPadding = EdgeInsets.symmetric(horizontal: 16.0)` if you didn't use the `itemPadding` parameter.

To make your dropdownlist's width dynamic and your elements fit into the dropdown, use `itemPadding: EdgeInsets.zero`.
In this case, To add padding to your elements wrap your `Text` widget that you pass to `items` parameter with padding. I think this will solve your issue.

**Comment by ihorkozar** [comment]
@AhmedLSayed9 Thanks, your advice helped a lot. 
It may be worth passing these additional indents immediately in the library, this would be a good default solution.

**Comment by AhmedLSayed9** [comment]
The problem is if we add padding to the width immediately in the library, then static width won't be accurate. I'll try to find if we could make it work without changing static width
