### ISSUE TITLE
Center label text with icon

### ISSUE THREAD

**Issue by mic16** [AhmedLSayed9/dropdown_button2#29]
Hello,

I've recently started work on a new mobile app and I am using the dropdown_button2 widget. For the most part it works great, better than the widget provided by Flutter, but there's one issue that's annoying me a bit.

I'm trying to center the label text (the selected value) but the problem is when I use an Icon whilst trying to center the text, the alignment.center takes into account the icon when centering which results into the following.

![flutter app](https://user-images.githubusercontent.com/45202132/167855125-01cdb7f8-4c49-4329-9305-588a849eee51.jpg)

Technicaly it has centered both elements, but I want the icon to be on the far right whilst having the text be centered with the cog icon just above. I'm not sure if this is somehow possible, but I've tried for a couple of hours now to try and center it but it doesn't seem to be possible at the moment.

I've tried adding some padding so that the text is centered but what happens then is the list of elements has more spacing on the left than on the right.

![flutter app 2](https://user-images.githubusercontent.com/45202132/167856616-15a04c91-3762-4ca8-93ff-5d0882191917.jpg).

And I've also tried removing the icon from the widget and putting it inside a row with dropdown_button2 but what happens then is when I click on the icon, it doesn't open the dropdown menu.

Thanks in advance for the help.

**Comment by mic16** [comment]
Maybe it would be possible to use a Stack widget and give the icon and text their own alignment properties ?

**Comment by AhmedLSayed9** [comment]
Use `selectedItemBuilder` to achieve that "it controls how the selected item will be displayed on button". This is what you need to add:
```
selectedItemBuilder: (context) {
  return items.map<Widget>((String item) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.only(left: 24.0),
        child: Text(
          item,
          textAlign: TextAlign.center,
        ),
      ),
    );
  }).toList();
},
```
24.0 left padding same as the default size of the icon so that your label will be perfectly centered.
