### ISSUE TITLE
dropdown_button2 and divider

### ISSUE THREAD

**Issue by sergeyAx7007** [AhmedLSayed9/dropdown_button2#3]
hello. I use your dropdown_button2 v.1.0.7 library, it is very cool and convenient. Thanks to it, very convenient and beautiful menus are obtained. But I noticed such a nuance, I need to make the dividers in the menu equal to the width of the menu, and the edges of the menu rounded. These are the conditions of the application design. If I do this, then when scrolling through the menu, the list separators go beyond the menu boundaries. Can this be fixed? Thanks.

**Comment by AhmedLSayed9** [comment]
Hi @sergeyAx7007,
Thanks for your kind words.
This is how the flutter's core dropdown menu painter works but I'll look into this in the next few days and see what I can do.
