### ISSUE TITLE
how to change the drop down locale

### ISSUE THREAD

**Issue by mo7amedaliEbaid** [AhmedLSayed9/dropdown_button2#310]
Is there any way to change the locale of this drop down button?
 I mean that this icon
 ```dart
IconStyleData(
            icon: Icon(
              Icons.arrow_drop_down_sharp,
            ),
            iconSize: 30,
            iconEnabledColor: Colors.black,
            iconDisabledColor: Colors.grey,
          )
   ```
would be right in case of english and left in case of arabic

**Comment by AhmedLSayed9** [comment]
You can wrap DropdownButton2 with Directionality if you'd like to override the default direction.
