### ISSUE TITLE
Open Dialog Blur/Darken Background similar behaviour for dropdown_button2? 

### ISSUE THREAD

**Issue by wagmi-ltd** [AhmedLSayed9/dropdown_button2#35]
By using a dialog you it can be seen that the background turns black transparent when a modal is opened.
Can we have the same using dropdown_button2 ?  
Dropdown menu appears but having the ability to blur the background would be helpful.
Thanks

**Comment by AhmedLSayed9** [comment]
To have the same black transparent of the Dialogs set `barrierColor` parameter to `Colors.black54`
