### ISSUE TITLE
searchbar for a long list with objects instead of string

### ISSUE THREAD

**Issue by thorizer** [AhmedLSayed9/dropdown_button2#36]
This is by far the best dropdown menu in pub.dev. 

- adding list of Objects instead of list of strings and adding a required label (ex Object.name)

- i have a lot of duplicate names, using only strings is not an option

- Adding an optional searchBar to filter items in a long list would make it perfect

**Comment by AhmedLSayed9** [comment]
Hi @thorizer,
You don't have to use list of strings. `items` parameter takes `List<DropdownMenuItem<T>>` so the DropdownMenuItem can represent any object. But, You've to set unique value for each item. For Example:

```
items: items
    .map((item) => DropdownMenuItem<SomeClass>(
          value: SomeClass.uniqueValue,
          child: Text(
            SomeClass.text,
          ),
        ))
    .toList(),
```

For adding search feature, I'll see If we could add it without affecting the overall performance. Thanks for the suggestion.

**Comment by thorizer** [comment]
@AhmedLSayed9 SomeClass.uniqueValue doesn't work. value should be the same type as SomeClass

![Code_IOwX4YHin9](https://user-images.githubusercontent.com/13587810/172742275-8392e776-5238-4594-b90a-c29063852a82.png)

**Comment by AhmedLSayed9** [comment]
Check example 5 for using DropdownButton2 as Searchable Dropdown :wink:
