### ISSUE TITLE
RenderFlex overflowed error

### ISSUE THREAD

**Issue by govindmaheshwari2** [AhmedLSayed9/dropdown_button2#37]
In Dropdown2 items if we add
`DropdownButton2(
                                    dropdownWidth:
                                        MediaQuery.of(context).size.width * 0.6,
                                    buttonWidth:
                                        MediaQuery.of(context).size.width * 0.6,
...
DropdownMenuItem<String>(
                                        child: Text(
                                          list[i],
                                          style: GoogleFonts.inter(),
                                          overflow: TextOverflow.ellipsis,
                                          maxLines: 1,
                                        ),
                                        value: list[i],
                                      ),
...
`
and one of the item has like 200 characters then DropdownMenuItem rendered it with overflow type ellipses but button width will show error of renderFlex overflow.
![IMG_4269](https://user-images.githubusercontent.com/45732601/172032323-f9362bb3-49a8-408c-bfc2-e8405fed05fe.jpg)

**Comment by AhmedLSayed9** [comment]
Have you set `isExpanded` parameter to true?

**Comment by govindmaheshwari2** [comment]
Thank you for help

**Comment by govindmaheshwari2** [comment]
Suggestion: set default value of isExpanded to true

**Comment by AhmedLSayed9** [comment]
> Suggestion: set default value of isExpanded to true @AhmedLSayed9

I'll consider if we can change it in next update, Thanks!
