### ISSUE TITLE
Question - menu shadow

### ISSUE THREAD

**Issue by Aljnk** [AhmedLSayed9/dropdown_button2#40]
Is it possible to change the shadow color of the DropdownButton2 menu?

![Screenshot_2](https://user-images.githubusercontent.com/11256478/173287065-d2a0861a-1a6d-4412-a014-4b1647cb94f5.png)

**Comment by AhmedLSayed9** [comment]
Yes. Use `dropdownDecoration parameter`. for example:
```
dropdownDecoration: BoxDecoration(
  boxShadow: [
    BoxShadow(
      offset: const Offset(0, 6),
      blurRadius: 5,
      color: Colors.red.withOpacity(0.3),
    ),
  ],
),
```

**Comment by Aljnk** [comment]
Oh, no. BoxDecoration doesn't work on dropdown menu (only dropdown button) - shadow is still black

![Screenshot_3](https://user-images.githubusercontent.com/11256478/173318762-e1584453-b0e2-4c34-a15c-32409198cd55.png)

**Comment by Aljnk** [comment]
Thancks a lot - work :)

Found some strange thng - buttonDecoration -> BoxShadow work if buttonElevation greater then 4. Maybe it will be interesting for you.

![p1](https://user-images.githubusercontent.com/11256478/173387044-87b7e367-8ed5-4be2-bc36-bc2a6290998d.png)

![p2](https://user-images.githubusercontent.com/11256478/173387049-bfe7bc68-0923-4e73-a69b-6eedc3c4727b.png)

**Comment by AhmedLSayed9** [comment]
Good Catch! this happens because buttonDecoration uses buttonElevation as its boxShadow.
Instead, it should use buttonElevation only if the buttonDecoration doesn't have any boxShadows. I'll update it.

**Comment by AhmedLSayed9** [comment]
Update to latest version. Now you don't have to use `buttonElevation` parameter if you're going to pass `boxShadow` for the `buttonDecoration`.
