### ISSUE TITLE
issue with the new search feature

### ISSUE THREAD

**Issue by thorizer** [AhmedLSayed9/dropdown_button2#41]
First of all, I'd like to thank you for implementing the new search feature.

There is one little issue, it won't work if the unique value is not the string inside the dropdown (id instead of name). 

which means I need to refilter again to get the name. It works but it is slow. 

Besides I need to return the whole object after selection which means I need to refilter again.

![Code_pjwKfMvLoz](https://user-images.githubusercontent.com/13587810/174439851-f3155408-6314-4fd5-a231-3c6fa9d1abff.png)

There is also a small visual issue, when the selected item is scrolled:
 

https://user-images.githubusercontent.com/13587810/174441913-ce69b419-370a-457b-ab8b-e819ce5bbb18.mp4

**Comment by AhmedLSayed9** [comment]
In this case, you need to use your Custom object say SomeClass as the value of your items. To achieve this correctly, you'll need to override `operator ==`, `hashCode` of SomeClass to make it pattern-matching. Or, use package like Freezed to achieve the same result easily.

Then, make these updates to your code:

```
items: items
    .map((item) => DropdownMenuItem<SomeClass>(
          value: item,
          child: Text(
            item.name,
          ),
        ))
    .toList(),

searchMatchFn: (item, searchValue){
    final itemValue = item.value as SomeClass;
    final itemName = itemValue.name;
    //continue with your code
},
```

For the visual issue, give your search container widget a color, as the default is transparent. You could give it color of `Theme.of(context).canvasColor` to take the same default color of the menu.

**Comment by thorizer** [comment]
> you'll need to override `operator ==`, `hashCode` of SomeClass to make it pattern-matching. Or, use package like Freezed to achieve the same result easily.

can I use Equatable for this? What do you mean by pattern matching? 
let's say I have a class called user that has id and name. How shall I proceed?

**Comment by AhmedLSayed9** [comment]
Yes, Equatable is another option.
Sorry, I've edited my comment it should be called immutable classes "comparable classes". Freezed and Equatable are tools to generate those immutable classes.

**Comment by AhmedLSayed9** [comment]
@thorizer Let me know if you still not able to make it work and share your full code sample
