### ISSUE TITLE
Error styling hint

### ISSUE THREAD

**Issue by haydgately** [AhmedLSayed9/dropdown_button2#43]
When I try to style hint I get the error: The argument type 'Text' can't be assigned to the parameter type 'String'

**Comment by AhmedLSayed9** [comment]
Can you share a sample code please?

**Comment by haydgately** [comment]
` Container(
                                        width: MediaQuery.of(context).size.width - 48,
                                        height: 48,
                                        child: CustomDropdownButton2(
                                          hint: 'Select Item',
                                          dropdownItems: items,
                                          selectedItemBuilder: (context) {
                                            return items.map<Widget>((String item) {
                                              return Padding(
                                                padding: const EdgeInsets.only(top: 12.0),
                                                child: Text(
                                                  item,
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(color: Theme.of(context).colorScheme.onBackground, fontSize: 14),
                                                ),
                                              );
                                            }).toList();
                                          },
                                          icon: Icon(
                                            Icons.arrow_drop_down,
                                            color: Theme.of(context).colorScheme.onBackground,
                                            size: 24.0,
                                          ),
                                         
                                          value: selectedValue,
                                          onChanged: (value) {
                                            setState(() {
                                              selectedValue = value;
                                            });
                                          },
                                        ),
                                      ),`

**Comment by haydgately** [comment]
> ` Container(
>                                         width: MediaQuery.of(context).size.width - 48,
>                                         height: 48,
>                                         child: CustomDropdownButton2(
>                                           hint: 'Select Item',
>                                           dropdownItems: items,
>                                           selectedItemBuilder: (context) {
>                                             return items.map<Widget>((String item) {
>                                               return Padding(
>                                                 padding: const EdgeInsets.only(top: 12.0),
>                                                 child: Text(
>                                                   item,
>                                                   textAlign: TextAlign.center,
>                                                   style: TextStyle(color: Theme.of(context).colorScheme.onBackground, fontSize: 14),
>                                                 ),
>                                               );
>                                             }).toList();
>                                           },
>                                           icon: Icon(
>                                             Icons.arrow_drop_down,
>                                             color: Theme.of(context).colorScheme.onBackground,
>                                             size: 24.0,
>                                           ),
>                                          
>                                           value: selectedValue,
>                                           onChanged: (value) {
>                                             setState(() {
>                                               selectedValue = value;
>                                             });
>                                           },
>                                         ),
>                                       ),`

This works fine

**Comment by haydgately** [comment]
`Container(
                                        width: MediaQuery.of(context).size.width - 48,
                                        height: 48,
                                        child: CustomDropdownButton2(
                                          hint: Text("Hello World"),
                                          dropdownItems: items,
                                          selectedItemBuilder: (context) {
                                            return items.map<Widget>((String item) {
                                              return Padding(
                                                padding: const EdgeInsets.only(top: 12.0),
                                                child: Text(
                                                  item,
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(color: Theme.of(context).colorScheme.onBackground, fontSize: 14),
                                                ),
                                              );
                                            }).toList();
                                          },
                                          icon: Icon(
                                            Icons.arrow_drop_down,
                                            color: Theme.of(context).colorScheme.onBackground,
                                            size: 24.0,
                                          ),
                                          value: selectedValue,
                                          onChanged: (value) {
                                            setState(() {
                                              selectedValue = value;
                                            });
                                          },
                                        ),
                                      ),`

**Comment by haydgately** [comment]
> `Container(
>                                         width: MediaQuery.of(context).size.width - 48,
>                                         height: 48,
>                                         child: CustomDropdownButton2(
>                                           hint: Text("Hello World"),
>                                           dropdownItems: items,
>                                           selectedItemBuilder: (context) {
>                                             return items.map<Widget>((String item) {
>                                               return Padding(
>                                                 padding: const EdgeInsets.only(top: 12.0),
>                                                 child: Text(
>                                                   item,
>                                                   textAlign: TextAlign.center,
>                                                   style: TextStyle(color: Theme.of(context).colorScheme.onBackground, fontSize: 14),
>                                                 ),
>                                               );
>                                             }).toList();
>                                           },
>                                           icon: Icon(
>                                             Icons.arrow_drop_down,
>                                             color: Theme.of(context).colorScheme.onBackground,
>                                             size: 24.0,
>                                           ),
>                                           value: selectedValue,
>                                           onChanged: (value) {
>                                             setState(() {
>                                               selectedValue = value;
>                                             });
>                                           },
>                                         ),
>                                       ),`

This produces the error

**Comment by haydgately** [comment]
The error is consistent with the comments within the code saying it must be a string, however all the examples on https://github.com/AhmedLSayed9/dropdown_button2 have it as a widget and not a string

<img width="402" alt="Screenshot 2022-06-29 at 22 15 25" src="https://user-images.githubusercontent.com/8005325/176546172-17d40ab9-3b28-451b-aaf9-7000845bad23.png">

**Comment by haydgately** [comment]
I am trying to make the hint, and the list items a different colour, as they are black but I want to change them, I am struggling. I am also trying to change the list items background colour too, and invert the text color as I currently have this 

<img width="353" alt="Screenshot 2022-06-29 at 22 16 33" src="https://user-images.githubusercontent.com/8005325/176546313-d42ea1e1-9576-4971-a6f4-8803d474484e.png">

**Comment by haydgately** [comment]
@AhmedLSayed9 It is strange, did it used to just be a string and now instead change to accept a widget? I just saw that on a closed task someone refers to iconOnClick, but this isn't in my codebase if I search anywhere, its like whatever I have seems outdated? I am using dropdown_button2: ^1.6.2 though

**Comment by AhmedLSayed9** [comment]
Your using CustomDropdownButton2 not DropdownButton2. CustomDropdownButton2 was made as an example on how to make customized DropdownButton2 and use it through your app (like a wrapper). You should copy the CustomDropdownButton2 code to your lib files and customize it to your need (Pass hint as Widget instead of Text for example).

If your using just one DropdownButton2 in your app or a different styles dropdowns then no need to make CustomDropdownButton2 and use DropdownButton2 directly.
