### ISSUE TITLE
dropdown blur menu text

### ISSUE THREAD

**Issue by peterkuch** [AhmedLSayed9/dropdown_button2#47]
see my image how can I fix it? https://pub.dev/packages/dropdown_button2
![Screen Shot 2022-07-05 at 2 01 39 PM](https://user-images.githubusercontent.com/14107698/177269151-9436512b-f9bf-46cf-9af8-10c4ac65d4fb.png)

**Comment by peterkuch** [comment]
> What do you mean by blur menu text? I really don't get what you're trying to achieve here.

I mean when I try to build render HTML it's not smooth with text.

**Comment by AhmedLSayed9** [comment]
This is a Flutter issue not related to `DropdownButton2`. Check these refs, it might help: 
https://github.com/flutter/flutter/issues/32274
https://github.com/flutter/flutter/issues/89919
https://github.com/flutter/flutter/issues/58159

**Comment by peterkuch** [comment]
> This is a Flutter issue not related to `DropdownButton2`. Check these refs, it might help: [flutter/flutter#32274](https://github.com/flutter/flutter/issues/32274) [flutter/flutter#89919](https://github.com/flutter/flutter/issues/89919) [flutter/flutter#58159](https://github.com/flutter/flutter/issues/58159)

Thanks let me check.
