### ISSUE TITLE
Cupertino?

### ISSUE THREAD

**Issue by llorenzo** [AhmedLSayed9/dropdown_button2#48]
Hi, is this component relying on the MaterialApp or can you use it in CupertinoApp as well?

**Comment by AhmedLSayed9** [comment]
It's a Material Widget. But, you still can use it with `CupertinoApp` By wrapping it with `Material` Widget.

**Comment by llorenzo** [comment]
So how would you wrap it? Do you have a short example? Some component rely on the Material Theme which you don't have in an CupertinoApp.

**Comment by AhmedLSayed9** [comment]
```
Material(
      child: DropdownButtonHideUnderline(
        child: DropdownButton2(
          items: items,
          value: selectedValue,
          onChanged: (value) {},
        ),
      ),
    )
```

It'll use default Material Theme values for its styling.

**Comment by AhmedLSayed9** [comment]
```
Material(
      child: Theme(
        data: ThemeData(
          primarySwatch: Colors.grey,
          //Add your desired theme data
        ),
        child: DropdownButtonHideUnderline(
          child: DropdownButton2(
            items: items,
            value: selectedValue,
            onChanged: (value) {},
          ),
        ),
      ),
    ),
```

Also, here's how you could change the theme for DropdownButton2.
