### ISSUE TITLE
In the dialog DropdownButton2, change the value in the item state, and the corresponding value in the hint will not change until the dialog is reopened

### ISSUE THREAD

**Issue by zhengxiaoguan** [AhmedLSayed9/dropdown_button2#5]

**Comment by zhengxiaoguan** [comment]
ShowDialog(
child:DropdownButton2(
                    hint: Container(
                      child: Text(state.obj.selectValue), 
                    ),
                    items:ctx.state.valueList.map((Object obj){
                      return DropdownMenuItem<Object>(
                        value: obj,
                        child: Container(
                          child: Text(obj.selectValue),
                        ),
                      );
                    }).toList(),
                    onChanged: (obj) {
                        dispatch(actioncreator.update(obj));
                    },
                  ),
);

**Comment by AhmedLSayed9** [comment]
Hi @zhengxiaoguan,
Sorry for the delay in responding. You should use `StatefulBuilder` anywhere inside `showDialog` but to be as a parent of the `DropdownButton2` widget to let the widget tree defined under `StateFulBuilder` builder updates. You can do like the code below but use `setState` from the builder to update the value.

```
ShowDialog(
              child: StatefulBuilder(
                builder: (BuildContext context, StateSetter setState) {
                  return DropdownButton2(
                    hint: Container(
                      child: Text(state.obj.selectValue),
                    ),
                    items:ctx.state.valueList.map((Object obj){
                      return DropdownMenuItem(
                        value: obj,
                        child: Container(
                          child: Text(obj.selectValue),
                        ),
                      );
                    }).toList(),
                    onChanged: (obj) {
                      dispatch(actioncreator.update(obj));
                    },
                  );
                }
              ),
            );
```

**Comment by zhengxiaoguan** [comment]
Thank you. I'll try

发自我的iPhone
