### ISSUE TITLE
Disable Attribute

### ISSUE THREAD

**Issue by osamasado** [AhmedLSayed9/dropdown_button2#52]
Hello,
Is there any way to make this input a disabled field?

Thanks

**Comment by AhmedLSayed9** [comment]
I guess you're talking about the dropdown menu items. If so, each `DropdownMenuItem` has `enabled` parameter which if you pass `false` to it, the item will be disabled.

**Comment by osamasado** [comment]
No, I mean the dropdown_button2, I want to make it disabled and enable it when I change another value.

**Comment by AhmedLSayed9** [comment]
Oh, Alright. If the onChanged callback is null or the list of DropdownButton2.items is null or empty then the dropdown button will be disabled.

**Comment by osamasado** [comment]
Ok, Thank you very much.
