### ISSUE TITLE
Extra space on top and bottom of the dropdown button

### ISSUE THREAD

**Issue by wongcheehong** [AhmedLSayed9/dropdown_button2#55]
There is extra space on top and bottom of the dropdown button when I use the DropdownButtonFormField2 and seem like cannot be removed.
![Simulator Screen Shot - iPhone 13 Pro - 2022-07-26 at 19 40 09](https://user-images.githubusercontent.com/11075969/180997688-f63049eb-23cb-42c9-8da9-433799e7bd67.png)

**Comment by AhmedLSayed9** [comment]
add `isDense: true` `contentPadding: EdgeInsets.zero` for the `decoration` parameter.
add padding for the button using `buttonPadding` and use `buttonHeight` to increase the button's height.
