### ISSUE TITLE
contentPadding affect the alignment of dropdown as well

### ISSUE THREAD

**Issue by wongcheehong** [AhmedLSayed9/dropdown_button2#58]
The content padding also affect the alignment dropdown list and inkwell with this content padding set. I would like to give some left padding to the error text but it affect the dropdown also
```
DropdownButtonFormField2<String>(
  decoration: InputDecoration(
    isDense: true,
    contentPadding: EdgeInsets.only(left: 25),
  ),
  ...
```
![Simulator Screen Shot - iPhone 13 Pro - 2022-07-29 at 12 42 19](https://user-images.githubusercontent.com/11075969/181684321-3b68be3c-a901-4d87-8d9b-ae62720e6b37.png)

**Comment by AhmedLSayed9** [comment]
You cannot give padding to the error text individually as the widget responsible for rendering the error string is `InputDecorator`. It's a Flutter related issue, you cannot do that with `DropdownButton` or `TextFormField` too.

You've 2 solutions:
1. Use a hacky solution by returning error string in your validator as: `return '           ' + 'error text';`
2. Make a custom error widget.

Hope that helps.
