### ISSUE TITLE
Tappable area not expandable

### ISSUE THREAD

**Issue by SirBarksALot** [AhmedLSayed9/dropdown_button2#61]
New version makes the tappable area shrink, which makes the widget unsuable.
How it is now (1.7.1) - only hint widget height tappable:
![image](https://user-images.githubusercontent.com/44412197/182614092-9941a551-2061-4c66-ad23-a9a22a7b074a.png)

How it should be (1.6.3) - whole button tappable:
![image](https://user-images.githubusercontent.com/44412197/182614222-8f39138b-9267-48f6-847f-4c58ba669a37.png)

It worked correctly in 1.6.3 and it doesn't in 1.7.1 (didn't check 1.7.0 though yet). Exactly same code and hint widget is Text()

**Comment by AhmedLSayed9** [comment]
That was necessary update to fix #56 and I don't find any other approach to fix it without affecting that you can't use `padding` and `prefixIcon` inside decoration parameter. To achieve the same result of (1.6.3):

Use `isDense: true` and `contentPadding: EdgeInsets.zero` inside decoration and instead (to add padding) add Horizontal padding using `buttonPadding` parameter and Vertical padding by increasing `buttonHeight`. That is necessary so that the whole TextField Button become clickable, and also the dropdown menu open under the whole TextField Button.

**Comment by SirBarksALot** [comment]
Still doesn't help, but whatever, I can live with errors looking weird on 1.6.3.

**Comment by AhmedLSayed9** [comment]
It should work. Can you share a sample code?

**Comment by AhmedLSayed9** [comment]
On 1.6.3 you’ll face 2 issues when the error text is applied:
1. The tappable area mentioned in the issue above.
2. The menu will open below error text not below the button.
The new update fixes both issues but we’ve to use `buttonPadding` and `buttonHeight` to control the button padding instead of contentPadding inside decoration parameter.

**Comment by SirBarksALot** [comment]
Nothing fancy (I use GetX for state managment so the widget is wrapped in Obx()):
```dart
//Functions
  List<DropdownMenuItem<String>> _addDividersAfterItems(List items) {
    List<DropdownMenuItem<String>> menuItems = [];
    for (var item in items) {
      menuItems.addAll(
        [
          DropdownMenuItem<String>(
            value: item,
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8.0),
              child: Text(item),
            ),
          ),
          //If it's last item, we will not add Divider after it.
          if (item != items.last)
            const DropdownMenuItem<String>(
              enabled: false,
              child: Divider(),
            ),
        ],
      );
    }

    return menuItems;
  }

  List<int> _getDividersIndexes(items) {
    List<int> dividersIndexes = [];
    for (int i = 0; i < (items.length * 2) - 1; i++) {
      //Dividers indexes will be the odd indexes
      if (i.isOdd) {
        dividersIndexes.add(i);
      }
    }

    return dividersIndexes;
  }

// Controller
final RxList<String> sexSelection = ['Male', 'Female'].obx;

// Widget
DropdownButtonFormField2(
    isExpanded: true,
    dropdownElevation: Theme.of(context).popupMenuTheme.elevation!.round(),
    dropdownDecoration: BoxDecoration(
        borderRadius: BorderRadius.circular(4.0),
    ),
    hint: Text("Select sex"),
    value: controller.sexValue.value,
    customItemsIndexes: _getDividersIndexes(controller.sexSelection),
    customItemsHeight: 4,
    items: _addDividersAfterItems(controller.sexSelection),
    onChanged: (String? v) => controller.sexValue.value =v,
  ),
```
I have tried a lot of things to make 1.7.1 work, but to no avail. Would it be possible to somehow steer the DropdownButtonFormField2 to take button buttonHeight from default of material's DropdownButtonFormField, so they look the same by default?

**Comment by AhmedLSayed9** [comment]
You've to add decoration parameter with `isDense: true` and `contentPadding: EdgeInsets.zero`, so your DropdownButtonFormField2 should be:
```
DropdownButtonFormField2(
    isExpanded: true,
    decoration: InputDecoration(
      isDense: true,
      contentPadding: EdgeInsets.zero,
    ),
    //This increase button Height (Vertical Padding)
    buttonHeight: 42,
    //This add Horizontal Padding
    buttonPadding: EdgeInsets.symmetric(horizontal: 12),
    dropdownElevation: Theme.of(context).popupMenuTheme.elevation!.round(),
    dropdownDecoration: BoxDecoration(
        borderRadius: BorderRadius.circular(4.0),
    ),
    hint: Text("Select sex"),
    value: controller.sexValue.value,
    customItemsIndexes: _getDividersIndexes(controller.sexSelection),
    customItemsHeight: 4,
    items: _addDividersAfterItems(controller.sexSelection),
    onChanged: (String? v) => controller.sexValue.value =v,
  ),
```

I didn't get what you meant by "take button buttonHeight from default of material's DropdownButtonFormField".
Anyway, DropdownButtonFormField2 is the same as material's DropdownButtonFormField but with some changes/fixes and extra parameters to be customizable. It was using the same approach for button's InputDecoration on 1.6.3 but as said that approach is facing the issues mentioned above. That mean DropdownButtonFormField from material is facing the same issues too (https://github.com/flutter/flutter/issues/106659).

On 1.7.1, These issues were fixed and we can use buttonPadding/buttonHeight to adjust button's padding (Also, You've to use decoration with `isDense: true` and `contentPadding: EdgeInsets.zero`).
