### ISSUE TITLE
How to create drop up Suggetions

### ISSUE THREAD

**Issue by vinodh013** [AhmedLSayed9/dropdown_button2#63]
How to create drop-up TextField in Flutter

The user starts typing in the field and the suggestions should come in a drop-up under the field with a limit of 5 suggestions.

<img width="380" alt="Screenshot 2022-06-09 at 14 12 34" src="https://user-images.githubusercontent.com/65361302/183096340-04dd0ed1-f987-4c0f-8155-e00f20968792.png">

**Comment by AhmedLSayed9** [comment]
I think you're looking for something like `Autocomplete` from Flutter:
https://api.flutter.dev/flutter/material/Autocomplete-class.html
