### ISSUE TITLE
Dropdown Direction

### ISSUE THREAD

**Issue by mack-at-pieces** [AhmedLSayed9/dropdown_button2#64]
Hey! Love this package and have found it to be super useful, so thank you!

I'm curious if there's a way (that I can't seem to find) or a plan to customize the direction of the dropdown?

For example in the screenshot below, you see it opens to the bottom-right, whereas it would be ideal to configure this to open bottom-left.

I tried to use the `offset` property, but couldn't get that to work.

Thanks so much!

<img width="602" alt="Screen Shot 2022-08-05 at 3 42 06 PM" src="https://user-images.githubusercontent.com/30325757/183149394-aef0ef30-af4f-47ec-aacf-62c03065321a.png">

**Comment by AhmedLSayed9** [comment]
My pleasure @mack-at-pieces.

Here's how to make it works:
- use `Offset` parameter and adjust the dx value, it should be: Offset(YourCustomButtonWidth - dropdownWidth, 0)
i.e: if customButton width is 46 and dropdownWidth is 160, Your offset should be `Offset(46 - 160, 0)` which equal `Offset(-114, 0)`

**Comment by mack-at-pieces** [comment]
@AhmedLSayed9 amazing - thank you for the quick response. That worked!
