### ISSUE TITLE
Incorrect clip behaviour for 1.7.0 and above

### ISSUE THREAD

**Issue by AndreiRoze** [AhmedLSayed9/dropdown_button2#65]
I have incorrect clip behaviour for DropdownButtonFormField2 for version 1.7.0 and above. You can see it on screenshots, when i press on DropdownButtonFormField2 ripple effect move outside of button.

Screenshoot from 1.6.3 (Correct behaviour):
![1 6 3](https://user-images.githubusercontent.com/53582576/183655758-b9e4e927-a546-44bf-9689-79c4f59133b8.jpg)

Screenshoot from 1.7.0 (Unexpected behaviour):
![1 7 0](https://user-images.githubusercontent.com/53582576/183655844-ee4309a9-73e0-4a64-a2e7-4ebbbdd5bd76.jpg)

Code(Sorry for screenshot):
![code](https://user-images.githubusercontent.com/53582576/183656686-672d151d-65bb-49fc-8fc1-a82057ed2b1f.png)

**Comment by AhmedLSayed9** [comment]
just add buttonDecoration with same borderRadius of your Border, like this:
```
buttonDecoration: BoxDecoration(
  borderRadius: BorderRadius.circular(8.0),
),
```

**Comment by AndreiRoze** [comment]
Thank you for you response, i also have strange behaviour for ripple effect in 1.7.1 version, in 1.7.0 is was correct.

Screenshoot from 1.7.0 (Correct behaviour):
![1 7 0](https://user-images.githubusercontent.com/53582576/184100488-7dd455e5-929b-499d-b1c3-9576a27f8210.jpg)

Screenshoot from 1.7.1 (Unexpected behaviour):
![1 7 1](https://user-images.githubusercontent.com/53582576/184100598-6d8a1717-df53-4547-9d2c-ba7d0223c536.jpg)

Code:
```
                      DropdownButtonFormField2<String>(
                        dropdownMaxHeight: MediaQuery.of(context).size.height / 2,
                        dropdownDecoration: BoxDecoration(borderRadius: BorderRadius.circular(8)),
                        buttonDecoration: BoxDecoration(borderRadius: BorderRadius.circular(8)),
                        dropdownOverButton: true,
                        scrollbarRadius: const Radius.circular(8),
                        isExpanded: true,
                        decoration: InputDecoration(
                          contentPadding: const EdgeInsets.all(8),
                          filled: true,
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8),
                            borderSide: const BorderSide(color: Colors.transparent),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(8),
                            borderSide: const BorderSide(color: Colors.transparent),
                          ),
                        ),
```

**Comment by AhmedLSayed9** [comment]
Add `isDense: true` and `contentPadding: EdgeInsets.zero` inside decoration and instead (to add padding) add Horizontal padding using `buttonPadding` parameter and Vertical padding by increasing `buttonHeight`. That is necessary so that the whole TextField Button become clickable, and also the dropdown menu open under the whole TextField Button.

**Comment by AndreiRoze** [comment]
@AhmedLSayed9 thanks for fast reply, it's work, but looks like ripple effect is offset to top on 1px, it's really hard to see, but i can see it better if set bright color for borders. I try to show you where exactly ripple effect is shifted on screenshot. Little bit pixel perfect.
![Screenshot_20220811-112926](https://user-images.githubusercontent.com/53582576/184106124-63c4aabf-516d-4c7a-801b-22213a3a7a09.jpg)
