### ISSUE TITLE
Default width not working correctly

### ISSUE THREAD

**Issue by vanth0me** [AhmedLSayed9/dropdown_button2#66]
Hello, 
Wanted to try this package because it doesn't force you to show the item field like the default button. Making my own proved harder than I thought respecting screen boundries.

Anyway I added the code and dropped in the items, but it's way too small. Increasing the size within the DropDownMenuItem doesn't seem to do much.

![image](https://user-images.githubusercontent.com/28623044/184663276-dedad5d0-c51c-49e0-9b62-fa794177b3a1.png)

This is the code:
```
DropdownButtonHideUnderline(
  child: DropdownButton2(
    value: widget.initialDropDownValue,
    itemPadding: EdgeInsets.zero,
    items: widget.dropDownItems!.entries
        .map(
          (e) => DropdownMenuItem(
            value: e.key,
            child: Text(
              e.value,
              style: poppins14Dark,
            ),
          ),
        )
        .toList(),
    customButton: _editIcon(),
    onChanged: (value) => widget.dropDownItemSelected?.call(value),
  ),
),
```

Thanks in advance!

**Comment by AhmedLSayed9** [comment]
You need to use `dropdownWidth` parameter, check example `6. DropdownButton2 as Popup menu button using customButton parameter` at README.

**Comment by vanth0me** [comment]
So there is no dynamic width for custom buttons, that's too bad but thanks for your answer.

**Comment by AhmedLSayed9** [comment]
There's no dynamic width for the dropdown menu at all, not just customButton. When you don't use `dropdownWidth` then its width will equal to button's width not a dynamic width.
