### ISSUE TITLE
dropdown does not seem to account for screen bottom padding.

### ISSUE THREAD

**Issue by SamiAlsubhi** [AhmedLSayed9/dropdown_button2#69]
the code used is the same as the example given for the form dropdown. the widget does not account for bottom padding and adjusts the dropdown position.
<img width="340" alt="Screen Shot 2022-08-25 at 10 05 46 AM" src="https://user-images.githubusercontent.com/2551232/186587670-140d4a69-bbaf-42b4-a760-62ab9aabd606.png">
Whereas the stock DropdownButton accounts for it.
<img width="352" alt="Screen Shot 2022-08-25 at 10 06 12 AM" src="https://user-images.githubusercontent.com/2551232/186587650-084a0459-bd74-4b78-b326-af65d9fd79f3.png">

**Comment by AhmedLSayed9** [comment]
close as duplicates of https://github.com/AhmedLSayed9/dropdown_button2/issues/34
