### ISSUE TITLE
itemHeight null value is not available

### ISSUE THREAD

**Issue by avdept** [AhmedLSayed9/dropdown_button2#71]
As per docs it states 

```
If null, then the menu item heights will vary according to each menu item's intrinsic height.

The default value is [kMinInteractiveDimension], which is also the minimum height for menu items.

If this value is null and there isn't enough vertical room for the menu, then the menu's initial scroll offset may not align the selected item with the dropdown button. That's because, in this case, the initial scroll offset is computed as if all of the menu item heights were [kMinInteractiveDimension].
```

However the type of itemHeight is `double`, not `double?`, so I can't make each item different height.
Am I missing something?

**Comment by AhmedLSayed9** [comment]
I'll update the doc of this part. 

Actually, `itemHeight` can't be null. If you've not used `itemHeight` parameter, it'll be the default `kMinInteractiveDimension` which is 48.0

**Comment by avdept** [comment]
So there's no way to set dynamic height to dropdown element?

**Comment by avdept** [comment]
Ok, thanks for answer, that makes sense. Basically I just have a list of elements which I need to display differently. IS there or do you plan for supporting known but different height elements? Like allow each `DropdownMenuItem` to have its own, known beforehand `height` prop ?

**Comment by AhmedLSayed9** [comment]
Let me think if we could add dynamic but predefined heights proper scrolling to the selectedItem.
