### ISSUE TITLE
 Error: The method 'clampDouble' isn't defined for the class '_DropdownMenuPainter'.

### ISSUE THREAD

**Issue by TRemigi** [AhmedLSayed9/dropdown_button2#74]
As far as I can tell, `clampDouble` needs to be imported from the [material_color_utilities](https://pub.dev/packages/material_color_utilities/install) package. I've created a branch which adds the dependency and implements in the problematic file, but I don't have rights to push the branch to the repo. If I can be added as a collaborator I'd be happy to submit the branch for review. Thanks.

**Comment by sagarstackapp** [comment]
i am facing same issue 
can i had soln for this

**Comment by AhmedLSayed9** [comment]
There's no need to add dependency on the [material_color_utilities](https://pub.dev/packages/material_color_utilities/install) package as `clampDouble` is already there on the current flutter stable channel.

All you need to do guys is run `flutter upgrade` command.

**Comment by AhmedLSayed9** [comment]
Check [this](https://github.com/flutter/flutter/pull/103559) conversation to find out more about the benefits of clampDouble over the old num.clamp

**Comment by jusuf-el** [comment]
Besides upgrading your Flutter version, downgrading the dependency version to 1.7.2 worked for me.

**Comment by AhmedLSayed9** [comment]
@jusuf-el Sure, as `clampDouble` has been added to 1.8.0 update.
But, You'll lose the advantage of the other updates too. It's better to keep everything up-to-date.

**Comment by jusuf-el** [comment]
@AhmedLSayed9 I agree 100%, but in case someone is not able to upgrade the Flutter version currently (as was the case with me today), this one can unblock you, at least temporarily.

**Comment by rizqiimani** [comment]
> Besides upgrading your Flutter version, downgrading the dependency version to 1.7.2 worked for me.

Already did a downgrade, but apparently it still exist in the hosted cache (`C:/Users/HOME/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/`) and had to delete it manually

I even already did `flutter clean` and Invalidate Caches of Android Studio

**Comment by AhmedLSayed9** [comment]
I guess as many people struggling with this, we should define `clampDouble` within DropdownButton2 library for the meantime.
