### ISSUE TITLE
Option Group (optgroup)

### ISSUE THREAD

**Issue by Aljnk** [AhmedLSayed9/dropdown_button2#75]
Is it possible to create a grouped list (with inactive labels inside the list) - like html optgroup?

Example:
```
<select>
	<option value="ALL">Show All</option>
	<optgroup label="Status">
		<option value="LIS1">Active</option>
		<option value="LIS2">Inactive</option>
	</optgroup>
	<optgroup label="Type">
		<option value="LST1">Good</option>
		<option value="LST2">Bad</option>
	</optgroup>
</select>
```
![Screenshot_1](https://user-images.githubusercontent.com/11256478/190071248-6d9b2863-203f-4a65-9d9c-75ef07e7e04f.jpg)

**Comment by AhmedLSayed9** [comment]
Check out example `3. DropdownButton2 with items of different heights like dividers`. You can do the same to make inactive labels with different style.
