### ISSUE TITLE
iOS error ？

### ISSUE THREAD

**Issue by pheromone** [AhmedLSayed9/dropdown_button2#8]
dropdown_button2: 1.1.1  #下拉框

![image](https://user-images.githubusercontent.com/14305431/154191874-939ecde0-6d09-45fc-bbc2-160a4fb256ee.png)

  
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/14305431/154191779-b2d94b08-4e59-4687-93f9-572d4b3c34a5.png">

**Comment by AhmedLSayed9** [comment]
You're using old flutter version "version 2.2.3" and the package depends on some core flutter fields which has been added after that version like "DropdownMenuItem".

Please update your flutter version to some newer version. You can upgrade to latest version by entering "flutter upgrade" in the terminal.
