### ISSUE TITLE
Feature request: multiple columns in dropdown list.

### ISSUE THREAD

**Issue by slavap** [AhmedLSayed9/dropdown_button2#80]
It would be nice to be able to customize dropdown list layout, on bigger resolutions it is easier to select items without need to scroll.

![image](https://user-images.githubusercontent.com/4129763/192672044-e012688f-919b-4fae-838c-ac1ce0c9556b.png)

![image](https://user-images.githubusercontent.com/4129763/192672342-8fcf78d0-b535-4213-ba5e-70cc3ddcf25d.png)

**Comment by AhmedLSayed9** [comment]
This is a real breaking change to make which has a very small use-cases and can be implemented with normal dialogs, for that reason I'm not interested to implement it to be honest.

You're free to contribute to implement this!

**Comment by slavap** [comment]
@AhmedLSayed9 
What about just adding a builder for the ability to customize ListView creation? I'm talking about this code:
```dart
                child: PrimaryScrollController(
                          controller: widget.route.scrollController!,
                          child: Scrollbar(
                            radius: widget.scrollbarRadius,
                            thickness: widget.scrollbarThickness,
                            thumbVisibility: widget.scrollbarAlwaysShow,
                            child: ListView(
                              // Ensure this always inherits the PrimaryScrollController
                              primary: true,
                              padding: widget.dropdownPadding ??
                                  kMaterialListPadding,
                              shrinkWrap: true,
                              children: _children,
                            ),
                          ),
                        ),
```
I'm sure that instantiating GridView instead of ListView may solve many specific cases.

**Comment by AhmedLSayed9** [comment]
> @AhmedLSayed9 What about just adding a builder for the ability to customize ListView creation? I'm talking about this code:
> 
> ```dart
>                 child: PrimaryScrollController(
>                           controller: widget.route.scrollController!,
>                           child: Scrollbar(
>                             radius: widget.scrollbarRadius,
>                             thickness: widget.scrollbarThickness,
>                             thumbVisibility: widget.scrollbarAlwaysShow,
>                             child: ListView(
>                               // Ensure this always inherits the PrimaryScrollController
>                               primary: true,
>                               padding: widget.dropdownPadding ??
>                                   kMaterialListPadding,
>                               shrinkWrap: true,
>                               children: _children,
>                             ),
>                           ),
>                         ),
> ```
> 
> I'm sure that instantiating GridView instead of ListView may solve many specific cases. Something like:
> 
> ```dart
> child: widget.listBuilder != null ? widget.listBuilder(_children, padding) : ListView(...);
> ```

It's not that easy.

The thing is, this will break many features of the package, i.e menu height & menu positioning. All that will need to be handled for the GridView option.

I'll see the chances of this being implemented.
