### ISSUE TITLE
Why the container color change to grey color when I click outside of the container. I have changed the Inkwell colors but this problem is still there 

### ISSUE THREAD

**Issue by debjeetdebnath** [AhmedLSayed9/dropdown_button2#81]

**Comment by debjeetdebnath** [comment]
here is the video I have uploaded to Google drive [https://drive.google.com/file/d/1HgDKfTLyB09VsTilSJEj0mtpZ3a2Tv77/view?usp=sharing](url)

**Comment by AhmedLSayed9** [comment]
Hi @debjeetdebnath
Was this closed on purpose?

**Comment by debjeetdebnath** [comment]
Ya It was closed on purpose.
Actually it was my fault, I didn't give much attention to container properties
