### ISSUE TITLE
[Question] How can I minimize the button width by Icon only?

### ISSUE THREAD

**Issue by burekas7** [AhmedLSayed9/dropdown_button2#82]
Hi,

My purpose is to set the button only by an icon, so its dimensions will be according to the Icon/Widget.
The meaning is that the width of the button should be shorter than the dropdown items width.
Is it possible?

Because the problem is that it set the min width of the button to be as the dropdown items width.

Edited: I tried to set buttomWidth, but when I get low then a specific value (100) I get overflow and the button still active but become invisible. And I get errors in the log regarding size issue and null values.

Thanks.

**Comment by AhmedLSayed9** [comment]
Hi @burekas7,
Have you checked example `6. DropdownButton2 as Popup menu button using customButton parameter` ?

**Comment by burekas7** [comment]
Strange, I did try it, but then there was bugs.
I tryied again after a day again and the 'customButton' is work.

By the way, when using 'customButton' does it ignor the 'buttonDecoration'?
So I need to wrap the icon with a container and set the decoration there instead?

**Comment by burekas7** [comment]
Another question (or you want to open in a seperate issue?)
Is there an option to open the items above the button? 
I know it calls DropDown :) but sometimes you may want to locate the button at the bottom, so it could be nice.
Currently it open the list on the icon (like stack, one on each other)

**Comment by AhmedLSayed9** [comment]
> Strange, I did try it, but then there was bugs. I tried it again after a day and the 'customButton' is working good.
> 
> By the way, when using 'customButton' does it ignor the 'buttonDecoration', 'buttonWidth' etc? So I need to wrap the icon with a container and set the decoration there instead?

Yes, That's true.

I'll close this as this is solved.

**Comment by AhmedLSayed9** [comment]
> Another question (or you want to open in a seperate issue?)
> Is there an option to open the items above the button?
> I know it calls DropDown :) but sometimes you may want to locate the button at the bottom, so it could be nice.
> Currently it open the list on the icon (like stack, one on each other)

You can use Offset parameter to change the menu position

**Comment by burekas7** [comment]
> > Another question (or you want to open in a seperate issue?)
> > Is there an option to open the items above the button?
> > I know it calls DropDown :) but sometimes you may want to locate the button at the bottom, so it could be nice.
> > Currently it open the list on the icon (like stack, one on each other)
> 
> You can use Offset parameter to change the menu position

When I put the button at the bottom of the screen and using the 'offset' option.
Only the 'dx' has an impact, but any value that I put for 'dy' (positive/negatice) doesn't do anything.

**Comment by AhmedLSayed9** [comment]
Read and apply this instruction: https://github.com/AhmedLSayed9/dropdown_button2/issues/34#issuecomment-1138727455

**Comment by AhmedLSayed9** [comment]
To open the menu right above the button, your dy value should equal to buttonHeight + MenuHeight.

**Comment by burekas7** [comment]
> To open the menu right above the button, your dy value should equal to buttonHeight + MenuHeight.

Thanks,
But as I said, I tried random values just to see some movement on y axis, but any value I put (100,200, etc.. and also -100, -200...) the list items doesn't move, still stay a the bottom.
(dx works fine)

**Comment by AhmedLSayed9** [comment]
Alright, can you please provide a working sample of your code in a new issue?
