### ISSUE TITLE
[Bug] offset dy doesn't work for some cases

### ISSUE THREAD

**Issue by burekas7** [AhmedLSayed9/dropdown_button2#85]
Hi,

When the DropDownItems are below the bottom of their parent / screen, the bottom position of their container is automatically attached to the bottom of their parent. And they are ovevrlay the button.

So my purpose is moving it by using the offset to be over the button.

But I found that when I put it in a Stack and position the button lower in the screen,
The dy offset doensn't move it (bottom: 0), or in some specific arrange of values for dy has effect while outside this arange it pinned to the bottom of the screen (bottom: > 0)

```
return Scaffold(
      appBar: AppBar(
        title: Text('Title'),
      ),
      body: SafeArea(
          child: Stack(
        children: [
          Positioned(
            bottom: 0,   //  <<<<<<==================
            right: 50,
            child: DropdownButton2(
              offset: const Offset(0, 110), //  <<<<<<==================
              underline: Container(),
              dropdownDecoration: BoxDecoration(
                borderRadius: BorderRadius.circular(14),
                color: Colors.redAccent,
              ),
              dropdownWidth: 150,
              customButton: Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(
                    color: Colors.black26,
                  ),
                  color: Colors.redAccent,
                ),
                child: const Icon(
                  Icons.sort,
                  color:
                      Colors.black,
                ),
              ),
              //dropdownOverButton: true,
              items: const [
                DropdownMenuItem(value: 1, child: Text("Item 1")),
                DropdownMenuItem(value: 2, child: Text("Item 2")),
                DropdownMenuItem(value: 3, child: Text("Item 3")),
              ],
              onChanged: (value) {},
            ),
          )
        ],
      )
    );
```

bottom = 0
non of the dy offset values has an effect, it always keep pinned to the bottom.

![image](https://user-images.githubusercontent.com/13424257/194709300-e3947515-7640-402d-b8e9-5d8f84753b49.png)![image](https://user-images.githubusercontent.com/13424257/194709278-d280ee58-9621-4dd3-bdf8-a03be4982804.png)

bottom = 50
dy does have an effect for these arrange of values: ~90-160, any value outside this range make the items to be pinned to the bottom
![image](https://user-images.githubusercontent.com/13424257/194709518-b2ca6c9c-c309-4c74-a5eb-1985505046e4.png)![image](https://user-images.githubusercontent.com/13424257/194709554-7bcdde23-ecb8-4401-b6bd-e4eeeaeeaea5.png)

**Comment by AhmedLSayed9** [comment]
Upgrade to 1.8.3. You'll be able to increase the value above 160 now

**Comment by burekas7** [comment]
> Upgrade to 1.8.3. You'll be able to increase the value above 160 now

Thanks, it's working now.
