### ISSUE TITLE
Height is misaligned compared to standard form fields

### ISSUE THREAD

**Issue by elliotrtd** [AhmedLSayed9/dropdown_button2#87]
I have a form where I'm looking to use both DropdownButtonFormField2 and some default TextFormField

When next to each other the misalignment between the 2 is quite obvious, I managed to get it "close" with some extra work but it's still kind of obvious. Maybe I'm missing something but it would be nice if the default builder was the same height / layout. Note I use a selectedItemBuilder to show just the ID, but the same occurs even without this (in fact worse because the text tries to wrap). 

*Ugh - pasting the code has killed the formatting - I made the edits bold*

Without additional code: 
![image](https://user-images.githubusercontent.com/43793032/194763852-b0d7df49-3523-4dcf-b3c3-7c2cfc28138c.png)
Code: 
Row(
                children: [
                  Expanded(
                    child: DropdownButtonFormField2<CostCode>(
                      isExpanded: true,
                      value: _costCode,
                      dropdownWidth: 300,
                      decoration: InputDecoration(
                        labelText: "Cost Code",
                        border: UnderlineInputBorder(),
                      ),
                      selectedItemBuilder: (context) {
                        return Provider.of<AppProvider>(context, listen: false)
                            .costCodes
                            .codes
                            .map((e) {
                          return Container(
                            alignment: Alignment.bottomLeft,
                            child: Text(
                              e.id.toString(),
                            ),
                          );
                        }).toList();
                      },
                      items: _codeOptions.map((e) {
                        return DropdownMenuItem(
                          enabled: e.type == "code",
                          child: Text(
                            "${e.id} - ${e.label}",
                            style: TextStyle(
                                fontWeight: e.type == "code"
                                    ? FontWeight.normal
                                    : FontWeight.bold),
                          ),
                          value: e,
                        );
                      }).toList(),
                      onChanged: (v) {
                        setState(() {
                          _costCode = v;
                        });
                      },
                    ),
                  ),
                  SizedBox(
                    width: 30,
                  ),
                  Expanded(
                    flex: 5,
                    child: TextFormField(
                      controller: _descriptionController,
                      decoration: InputDecoration(
                        labelText: "Description",
                        border: UnderlineInputBorder(),
                      ),
                    ),
                  ),
                ],
              ),

With additional code: 
![image](https://user-images.githubusercontent.com/43793032/194763895-dc73d81e-50d7-4811-b654-b1091bb9d58f.png)

Code: 
Row(
                **crossAxisAlignment: CrossAxisAlignment.end,**
                children: [
                  Expanded(
                    child: DropdownButtonFormField2<CostCode>(
                      isExpanded: true,
                      value: _costCode,
                      dropdownWidth: 300,
                      **buttonHeight: 25,**
                      decoration: InputDecoration(
                        labelText: "Cost Code",
                        border: UnderlineInputBorder(),
                      ),
                      selectedItemBuilder: (context) {
                        return Provider.of<AppProvider>(context, listen: false)
                            .costCodes
                            .codes
                            .map((e) {
                          return Container(
                            alignment: Alignment.bottomLeft,
                            child: Text(
                              e.id.toString(),
                            ),
                          );
                        }).toList();
                      },
                      items: _codeOptions.map((e) {
                        return DropdownMenuItem(
                          enabled: e.type == "code",
                          child: Text(
                            "${e.id} - ${e.label}",
                            style: TextStyle(
                                fontWeight: e.type == "code"
                                    ? FontWeight.normal
                                    : FontWeight.bold),
                          ),
                          value: e,
                        );
                      }).toList(),
                      onChanged: (v) {
                        setState(() {
                          _costCode = v;
                        });
                      },
                    ),
                  ),
                  SizedBox(
                    width: 30,
                  ),
                  Expanded(
                    flex: 5,
                    child: TextFormField(
                      controller: _descriptionController,
                      decoration: InputDecoration(
                        labelText: "Description",
                        **contentPadding: EdgeInsets.only(bottom: 15),**
                        border: UnderlineInputBorder(),
                      ),
                    ),
                  ),
                ],
              )

**Comment by elliotrtd** [comment]
I later realised that not even the default DropdownButtonFormField is aligned correctly, but the text alignment of the selected value is better, you can see the space between the label and value is pretty narrow. Making that larger would be an improvement already

**Comment by AhmedLSayed9** [comment]
Can you provider a working sample that can produce your issue? I can't run the code as it has lots of dependencies.
Also, you can add your code nicely by selecting the code then pressing `<>` in the comment tools or `cmd+e`.

**Comment by elliotrtd** [comment]
@AhmedLSayed9 - Ah sorry for the dependencies - it was too late when I wrote it and wanted to put something down, I'll get you a working sample later.

**Comment by AhmedLSayed9** [comment]
I'll close this for now. Feel free to re-open when your working sample is ready.
