### ISSUE TITLE
searchMatchFn not working in release mode of app

### ISSUE THREAD

**Issue by akshaynjarangal** [AhmedLSayed9/dropdown_button2#91]
`searchMatchFn` not working in `release` mode of app, works in `debug` mode, when search a value contains in `DropdownMenuItem` not working in `release` , in `debug` mode it's works perfect.

**Comment by AhmedLSayed9** [comment]
Can you please provide a working sample and your flutter doctor output?

**Comment by AhmedLSayed9** [comment]
I'll close this for now. Feel free to re-open when your working sample is ready.
