### ISSUE TITLE
QUESTION: use value pair for items

### ISSUE THREAD

**Issue by alexlovar** [AhmedLSayed9/dropdown_button2#93]
hello, how i can do to use the onchange event to get an associated value to the item?
for example:
items:
```
item1 , value on selection: A
item2 , value on selection: B
item3, value on selection: C
....
```
i want to display the dropdown text of the item title, but i need the on-selection value when the user selects an item from the list, how i can do this?
thanks

**Comment by AhmedLSayed9** [comment]
You need to use some class for the item instead of a String. check example `6. DropdownButton2 as Popup menu button` at ReadMe.

**Comment by alexlovar** [comment]
thank you @AhmedLSayed9
