### ISSUE TITLE
Issue: The named parameter 'searchController' isn't defined

### ISSUE THREAD

**Issue by alexlovar** [AhmedLSayed9/dropdown_button2#95]
hello, in the sample  5. DropdownButton2 as Searchable Dropdown: the follow parameters appear as undefined:
```
searchController
searchInnerWidget
searchMatchFn: 
onMenuStateChange:
```
is this plugin still support search?

thanks

**Comment by alexlovar** [comment]
i was using **custom**Dropdown but is defined for Dropdown

**Comment by AhmedLSayed9** [comment]
Exactly, CustomDropdownButton2 was made so that you can make the same idea with your preferred properties.
It’s just a wrapper around DropdownButton2.
