### ISSUE TITLE
Update items in searchMatchFn without tap dropdown again to show the menu items already updated

### ISSUE THREAD

**Issue by zae1403** [AhmedLSayed9/dropdown_button2#96]
I want to Update property items in searchMatchFn (get data to server by query). but to see the updated result, currently i must tap the dropdown again. any solution?

**Comment by AhmedLSayed9** [comment]
Can you please provide a working sample and more details?

**Comment by AhmedLSayed9** [comment]
I'll close this for now.
Feel free to re-open when there's enough information regarding the issue.
