### ISSUE TITLE
Rebuilds when rect has changed error

### ISSUE THREAD

**Issue by ronaldgosso** [AhmedLSayed9/dropdown_button2#97]
E/flutter (21608): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (21608): #0      DropdownButton2State.didChangeMetrics
package:dropdown_button2/dropdown_button2.dart:1544
E/flutter (21608): #1      WidgetsBinding.handleMetricsChanged
package:flutter/…/widgets/binding.dart:550
E/flutter (21608): #2      _invoke (dart:ui/hooks.dart:148:13)
E/flutter (21608): #3      PlatformDispatcher._updateWindowMetrics (dart:ui/platform_dispatcher.dart:246:5)
E/flutter (21608): #4      _updateWindowMetrics (dart:ui/hooks.dart:33:31)
E/flutter (21608):

How do I solve that, running Flutter 3.3.6 stable updated the dependency

**Comment by AhmedLSayed9** [comment]
I've tested it and couldn't produce the issue. What platform are you using?

**Comment by AhmedLSayed9** [comment]
I'll close this for now.
Feel free to re-open when there's enough information regarding the issue.
